---
sidebar: sidebar
permalink: ci_adm_before.html
keywords: ontap select
summary: xxxx
---

= Before you begin administering ONTAP Select
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After creating an ONTAP Select cluster, you can support the deployment by performing various administrative tasks. There are a few general considerations to be aware of.

== Before you begin

In general, the procedures you can perform using the Deploy web interface fall into one of three categories.

Deploy an ONTAP Select cluster::
You can deploy a single-node or multi-node cluster. See link:ti_deploy_cluster.html[Deploying an ONTAP Select cluster] for more information.

Perform a procedure with an existing ONTAP Select cluster::
The administrative procedures are organized in various categories, such as _Security_ and _Clusters_.

Perform a procedure on the Deploy utility::
There are several procedures specific to Deploy (such as changing the administrator's password).

== Administering ONTAP Select

There are many different administrative procedures available as part of supporting ONTAP Select. In addition, there are procedures specific to the Deploy administrative utility. The most important of these procedures are presented below. In general, all use the Deploy web user interface. An administrative process can consist of a single step-by-step task or a sequence of multiple tasks.

[NOTE]
You can also use the command line interface to administer ONTAP Select. See the section _Using the CLI_ for more information.

== Performing additional ONTAP configuration

After an ONTAP Select cluster is deployed, you can configure and manage the cluster just as you would a hardware-based ONTAP system. For example, you can use OnCommand System Manager or the ONTAP CLI to configure the ONTAP Select cluster.

==== NetApp client software

You can connect to ONTAP Select using the following supported NetApp client software:

* OnCommand System Manager
* OnCommand Unified Manager
* OnCommand Performance Manager
* OnCommand Insight
* OnCommand Workflow Automation
* SnapCenter
* Virtual Storage Console for VMware vSphere

To identify the supported versions of the client software, review the _NetApp Interoperability Matrix Tool_. If the client software supports ONTAP 9, then the same version is also supported with ONTAP Select.

[IMPORTANT]
The use of SnapCenter and the corresponding plug-ins requires server-based licenses. Storage system licensing of the SnapCenter plug-ins is not currently supported with ONTAP Select.

Any other NetApp client software that is not included in the list is not supported by ONTAP Select.

==== Possible configuration options

There are several options available when configuring the cluster, including the following:

* Creating the networking configuration
* Laying out your aggregates
* Creating the data Storage Virtual Machines (SVMs)

==== Purchased licenses with storage capacity

If you decided not to install the license files with storage capacity as part of deploying the ONTAP Select cluster, you must acquire and install the license files before the grace period expires for clusters running with a purchased license.

==== Mirrored aggregates

There are data spare disks created by the Deploy administration utility on each ONTAP Select node from the usable datastore space (such as, Pool0 and Pool1). To implement high availability for your data on a multi-node cluster, you must create a mirrored aggregate using these spares.
