---
sidebar: sidebar
permalink: ci_production_license.html
keywords: ONTAP Select
summary: xxx
---

= Production licenses
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After you determine that ONTAP Select is suitable for your organization, you can purchase the
licenses needed to support a production deployment. You must choose either the capacity tiers or
capacity pools licensing model as well as the storage capacity for each deployment.

=== Common licensing characteristics

The _capacity tiers_ and _capacity pools_ licensing models are very different in several respects. However, the two licensing models share several common characteristics, including:

* You must purchase one or more licenses as needed when deploying ONTAP Select in a production environment.

* The storage capacity for a license is allocated in 1 TB increments.

* The storage capacity identifies the raw capacity and corresponds to the total allowable size of the data disks available to the ONTAP Select virtual machine.

* All platform licensing offerings are supported (standard, premium, premium XL).

* You should contact your NetApp account team or partner for assistance as needed when acquiring the necessary licenses.

* You must upload the license files to the Deploy administration utility, which then applies the licenses based on the licensing model.

* After installing and applying a license, you can add additional capacity by contacting your NetApp account team or partner to procure an updated license.

* Both nodes in an HA pair must have the same storage and license capacity.

* An ONTAP Select node that is initially deployed with a purchased license cannot be converted to an evaluation license.

=== Capacity tiers licensing model

There are several characteristics unique to the capacity tiers licensing model, including:

* You must purchase a license for each ONTAP Select node.

* Each capacity tier license has a storage capacity and is locked to a specific node.

* A nine-digit license serial number is generated by NetApp for each ONTAP Select node.

* The storage allocated to a node is perpetual (no renewal required).

* The node serial number is nine digits and equal to the license serial number.

* You can apply the license file during cluster deployment or within 30 days after creating a cluster.

=== Capacity pools licensing model

There are several characteristics unique to the capacity pools licensing model, including:

* You must purchase a license for each shared capacity pool.

* Each capacity pool license has a storage capacity and is locked to a specific License Manager instance.

* A nine-digit license serial number is generated by NetApp for each capacity pool.

* The storage allocated to a capacity pool is valid only for a specific time based on the purchase (renewal required).

* The node serial number is twenty digits and is generated by the License Manager based on the capacity pool license serial number.

* Each node automatically leases storage capacity for its local data aggregates from a shared capacity pool.

For more details on the capacity pools licensing model, see Understanding the capacity pools licensing model.

=== Understanding the platform license offerings

You can purchase an ONTAP Select capacity tier or capacity pool license in one of three platform capacity levels. These license offerings determine the capabilities of the hosts where you deploy ONTAP Select.

What a platform license offering provides::
A specific license offering defines and restrictions the capabilities of the hypervisor host in two areas:
* Instance type (CPU, memory)
* Additional features
The license offerings are arranged in an ascending order of capabilities from standard to premium XL. In general, the license option you choose grants you the capabilities of that level and all lower levels. For example, the premium level provides the capabilities of both premium and standard.

Standard::
The standard offering provides the following capabilities:
* Small instance type only
* Hard disk drives (HDD) only
* Local hardware RAID controller only
* vNAS

Premium::
The premium offering provides the following capabilities:
* Small or medium instance type
* Hard disk drives (HDD) or Solid state drives (SSD)
* Local hardware RAID controller or software RAID
* vNAS
* MetroCluster SDS

Premium XL::
The premium XL offering provides the following capabilities:
* Small, medium, or large instance type.
* Hard disk drives (HDD) or Solid state drives (SSD)
* Local hardware RAID controller or software RAID.
* vNAS
* MetroCluster SDS
When using the premium XL license with the large instance type, the following features are not supported:
* Hardware RAID
* vNAS
* KVM hypervisor
In short, ONTAP Select using the large instance type is only supported on ESXi with software RAID.
