---
sidebar: sidebar
permalink: concept_api_before_python.html
keywords: rest api, deploy rest api, rest, python, before you begin
summary: You must prepare the environment before running the sample Python scripts.
---

= Before you access the API using Python
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You must prepare the environment before running the sample Python scripts.

Before you run the Python scripts, you must make sure the environment is configured properly:

* The latest applicable version of Python2 must be installed.
The sample codes have been tested using Python2. They should also be portable to Python3, but have not been tested for compatibility.
* The Requests and urllib3 libraries must be installed.
You can use pip or another Python management tool as appropriate for your environment.
* The client workstation where the scripts run must have network access to the ONTAP Select Deploy virtual machine.

In addition, you must have the following information:

* IP address of the Deploy virtual machine
* User name and password of a Deploy administrator account
