---
sidebar: sidebar
permalink: concept_lic_cp_restrictions.html
keywords: license, licensing, Capacity Pools, restrictions
summary: The restrictions that apply when using the Capacity Pool licensing model are presented below.
---
= Deployment restrictions for ONTAP Select Capacity Pools licensing
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The restrictions that apply when using the Capacity Pool licensing model are presented below.

.Consistent licensing model per cluster

All of the nodes within a single ONTAP Select cluster must use the same licensing model, either Capacity Tiers or Capacity Pools. You cannot mix the licensing types for the nodes within a single cluster.

.All nodes in a cluster use the same License Manager instance

All the nodes with a Capacity Pool license in an ONTAP Select cluster must use the same License Manager instance. Because there is one instance of License Manager within each Deploy instance, this restriction is a restatement of the existing requirement that all nodes in a cluster must be managed by the same Deploy instance.

.One Capacity Pool per node

Each node can lease storage from exactly one Capacity Pool. A node cannot use two or more pools.

.Same pool for nodes in an HA pair

Both nodes in a single HA pair must lease storage from the same Capacity Pool. However, different HA pairs within the same cluster can lease storage from different pools managed by the same License Manager.

.Storage license duration

You must choose a license duration when acquiring the storage license from NetApp. For example, a license could be valid for one year.

.Data aggregate lease duration

When an ONTAP Select node requests a storage lease for a data aggregate, the License Manager provides a lease for a specific duration based on the configuration of the Capacity Pool. You can configure the lease duration for each pool between one hour and seven days. The default lease duration is 24 hours.

.Static IP address assigned to Deploy

You must assign a static IP address to the Deploy administration utility when Capacity Pools licensing is used.
