---
sidebar: sidebar
permalink: concept_lic_production.html
keywords: license, licensing, production, purchased, standard, premium, premium xl
summary: After you determine that ONTAP Select is suitable for your organization, you can purchase the licenses needed to support a production deployment. You must choose either the capacity tiers or capacity pools licensing model as well as the storage capacity for each deployment.
---
 
= Purchased licenses for production deployments
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After you determine that ONTAP Select is suitable for your organization, you can purchase the licenses needed to support a production deployment. You must choose either the capacity tiers or capacity pools licensing model as well as the storage capacity for each deployment.

== Common licensing characteristics

The _capacity tiers_ and _capacity pools_ licensing models are very different in several respects. However, the two licensing models share several common characteristics, including:

* You must purchase one or more licenses as needed when deploying ONTAP Select in a production environment.
* The storage capacity for a license is allocated in 1 TB increments.
* The storage capacity identifies the raw capacity and corresponds to the total allowable size of the data disks available to the ONTAP Select virtual machine.
* All platform licensing offerings are supported (standard, premium, premium XL).
* You should contact your NetApp account team or partner for assistance as needed when acquiring the necessary licenses.
* You must upload the license files to the Deploy administration utility, which then applies the licenses based on the licensing model.
* After installing and applying a license, you can add additional capacity by contacting your NetApp account team or partner to procure an updated license.
* Both nodes in an HA pair must have the same storage and license capacity.
* An ONTAP Select node that is initially deployed with a purchased license cannot be converted to an evaluation license.

== Capacity tiers licensing model

There are several characteristics unique to the capacity tiers licensing model, including:

* You must purchase a license for each ONTAP Select node.
* The minimum amount you can purchase is 1 TB.
* Each capacity tier license has a storage capacity and is locked to a specific node.
* A nine-digit license serial number is generated by NetApp for each ONTAP Select node.
* The storage allocated to a node is perpetual (no renewal required).
* The node serial number is nine digits and equal to the license serial number.
* You can apply the license file during cluster deployment or within 30 days after creating a cluster.

== Capacity pools licensing model

There are several characteristics unique to the capacity pools licensing model, including:

* You must purchase a license for each shared capacity pool.
* The minimum amount you can purchase is 2 TB.
* Each capacity pool license has a storage capacity and is locked to a specific License Manager instance.
* A nine-digit license serial number is generated by NetApp for each capacity pool.
* The storage allocated to a capacity pool is valid only for a specific time based on the purchase (renewal required).
* The node serial number is twenty digits and is generated by the License Manager based on the capacity pool license serial number.
* Each node automatically leases storage capacity for its local data aggregates from a shared capacity pool.

For more details on the capacity pools licensing model, see the _Capacity pools licensing model_ for more information.
