---
sidebar: sidebar
permalink: concept_lic_platforms.html
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl
summary: You can purchase an ONTAP Select capacity tier or capacity pool license in one of three platform capacity levels. These license offerings determine the capabilities of the hosts where you deploy ONTAP Select.
---

= Understand the platform license offerings
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can purchase an ONTAP Select capacity tier or capacity pool license in one of three platform capacity levels. These license offerings determine the capabilities of the hosts where you deploy ONTAP Select.

== What a platform license offering provides

A specific license offering defines and restrictions the capabilities of the hypervisor host in two areas:

* Instance type (CPU, memory)
* Additional features

The license offerings are arranged in an ascending order of capabilities from standard to premium XL. In general, the license option you choose grants you the capabilities of that level and all lower levels. For example, the premium level provides the capabilities of both premium and standard.

== Platform license offerings

There are three platform license offerings available.

=== Standard

The standard offering provides the following capabilities:

* Small instance type only
* Hard disk drives (HDD) only
* Local hardware RAID controller only
* vNAS

=== Premium

The premium offering provides the following capabilities:

* Small or medium instance type
* Hard disk drives (HDD) or Solid state drives (SSD)
* Local hardware RAID controller or software RAID
* vNAS
* MetroCluster SDS

=== Premium XL

The premium XL offering provides the following capabilities:

* Small, medium, or large instance type
* HDDs, SSDs, or NVMe drives
* Local hardware RAID controller or software RAID
* vNAS
* MetroCluster SDS

[NOTE]
Use of the large instance type or NVMe drives in an SW-RAID configuration is not supported on KVM.

// 2023-09-26, ONTAPDOC-1204
// 2023-12-12, ONTAPDOC-1525