---
sidebar: sidebar
permalink: concept_api_how_access.html
keywords: rest api, deploy rest api, rest, access, accessing, how to access
summary: Because of the inherent flexibility of REST web services, the ONTAP Select Deploy API can be accessed in several different ways.
---

= How to access the Deploy API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Because of the inherent flexibility of REST web services, the ONTAP Select Deploy API can be accessed in several different ways.

== Deploy utility native user interface

The primary way you access the API is through the ONTAP Select Deploy web user interface. The browser makes calls to the API and reformats the data according to the design of the user interface. You also access the API through the Deploy utility command line interface.

== ONTAP Select Deploy online documentation page

The ONTAP Select Deploy online documentation page provides an alternative access point when using a browser. In addition to providing a way to execute individual API calls directly, the page also includes a detailed description of the API, including input parameters and other options for each call. The API calls are organized into several different functional areas or categories.

== Custom program

You can access the Deploy API using any of several different programming languages and tools. Popular choices include Python, Java, and cURL. A program, script, or tool that uses the API acts as a REST web services client. Using a programming language allows you to better understand the API and provides an opportunity to automate the ONTAP Select deployments.
