---
sidebar: sidebar
permalink: concept_lic_evaluation.html
keywords: license, licensing, evaluation, upgrade license
summary: You can use an evaluation license if you want to evaluate ONTAP Select before making the decision to purchase. The evaluation license is included with the ONTAP Select Deploy administration utility and is automatically applied to each ONTAP Select node as part of an evaluation deployment.
---
= Evaluation licenses for ONTAP Select deployments
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can deploy ONTAP Select with an evaluation license or a purchased license. The license you choose must apply to each of the nodes in the ONTAP Select cluster and therefore to the entire cluster. You can use an evaluation license if you want to evaluate ONTAP Select before making the decision to purchase. The evaluation license is included with the ONTAP Select Deploy administration utility and is automatically applied to each ONTAP Select node as part of an evaluation deployment.

[NOTE]
====
To download the ONTAP Select Deploy administration utility, you need the following:

* A  registered NetApp Support Site account. If you don't have an account, see https://mysupport.netapp.com/site/user/registration[User registration^]. 
* To https://mysupport.netapp.com/site/downloads/evaluation/ontap-select[accept the End User License agreement^] for an ONTAP Select deployment with an evaluation license.
====

There are several considerations when deploying and supporting an evaluation cluster:

* You can only use the cluster for evaluation purposes. You must not use a cluster with an evaluation license in a production environment.
* You should use the ONTAP Select Deploy administration utility as follows when configuring each host:
** Don't supply a serial number
** Configure to use an evaluation license

== Licensing characteristics

The ONTAP Select evaluation license has the following characteristics:

* A production license with storage capacity isn't required
* The node serial number is twenty digits and automatically generated by ONTAP Select Deploy
+
(you don't acquire it directly from NetApp)
* The evaluation period provided by the license can be up to 90 days
* The maximum storage allocated by each node is the same as a production license

== Upgrade to a production license
You can upgrade an ONTAP Select evaluation cluster to use a production license. You should be aware of the following restrictions:

* You must use the Deploy administration utility to perform the license upgrade
* You can use a Capacity Tier license, however Capacity Pools licensing isn't supported
* Each node must have enough storage allocated to support the minimum required for a production license, based on the cluster size

See link:task_adm_licenses.html[Convert an evaluation license to a production license] for more information.

.Related information

* link:concept_lic_production.html[Learn about licenses for production deployments]
* link:access-evaluation-software.html[Access the ONTAP Select evaluation software]
* link:deploy-evaluation-ontap-select-ovf-template.html[Deploy a 90-day evaluation instance of an ONTAP Select cluster]

// 2025 JAN 17, ONTAPDOC-2556
// 2024 NOV 18, ONTAPDOC-2547
// 2024 OCT 7,  ONTAPDOC-2010
// 2023-10-17, Removed mention of old OTS versions