---
sidebar: sidebar
permalink: concept_lic_cp_serial_number.html
keywords: license, licensing, Capacity Pools, node serial numbers
summary: With the Capacity Tiers licensing model, the nine-digit node serial number is the same as the license serial number assigned to the node. However, the serial numbers assigned to nodes using the Capacity Pools licensing model have a different format.
---
= Node serial numbers for ONTAP Select Capacity Pools licensing model
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
With the Capacity Tiers licensing model, the nine-digit node serial number is the same as the license serial number assigned to the node. However, the serial numbers assigned to nodes using the Capacity Pools licensing model have a different format.

The serial number of a node using Capacity Pools licensing has the following format:

`999 ppppppppp nnnnnnnn`

[NOTE]
Spaces have been added for clarity, but are not part of the actual serial number.

The following table describes each section of the node serial number from left to right.

[cols="15,85"*,options="header"]
|===
|Section
|Description

|'999'
|Constant three-digit value reserved by NetApp.

|ppppppppp
|Variable nine-digit license serial number assigned to the Capacity Pool by NetApp

|nnnnnnnn
|Variable eight-digit value generated by the License Manager for each node using the Capacity Pool

|===

CAUTION: When opening a case with NetApp support involving a node that uses a Capacity Pool license, you must provide the nine-digit Capacity Pool license serial number. You cannot provide the full twenty-digit node serial number. You can derive the license serial number from the node serial number by skipping the first three digits of the node serial number ('999') and extracting the next nine digits (ppppppppp).


// 2025 DEC 12, NADIAA updates