---
sidebar: sidebar
permalink: concept_lic_cp_benefits.html
keywords: license, licensing, capacity pools, benefits
summary: There are several benefits when using the capacity pools licensing model instead of the capacity tiers licensing model.
---

= Summary of benefits
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several benefits when using the capacity pools licensing model instead of the capacity tiers licensing model.

== More efficient use of storage capacity

When using capacity tiers licensing, you allocate a fixed storage capacity to each node. Any unused space cannot be shared with the other nodes and is effectively wasted. With capacity pools licensing, each node only consumes the capacity it needs, based on the size of the data aggregates.

And because the capacity is anchored in a central pool, it can be shared among many nodes in your organization.

== Significantly reduced administrative overhead resulting in lower cost

If you use capacity tier licenses, you must obtain and install a license for each node. When using capacity pools, there is one license for each shared pool. This can dramatically reduce the administrative overhead and result in lower cost.

== Improved usage metrics

The Deploy web user interface provides enhanced usage information for the capacity pools. You can quickly determine how much storage is used and available in a capacity pool, which nodes are using storage from a pool, and what pools a cluster is allocating capacity from.
