---
sidebar: sidebar
permalink: concept-capacity-pool-space.html
keywords: license, licensing, Capacity Pools, operation details
summary: The Capacity Pools licensing model is different from the Capacity Tiers model. Instead of a dedicating storage capacity to each individual node, the storage capacity is allocated to a pool and shared among many nodes. Additional components and processes have been created to support the Capacity Pools model.
---
= ONTAP Select Capacity Pools license capacity
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The licensed capacity for a Capacity Pool license is in full TiB amounts, with a minimum of 2 TiB. The usable capacity is the amount of licensed capacity divided by the overhead factor. The overhead factor differs between a single-node and multi-node (HA-pair based) clusters:

* Overhead factor for single-node clusters is 1.13
* Overhead factor for multi-node clusters is 2.67

To determine the usable space from licensed space, you divide the licensed space by the overhead factor, as shown in the following examples:

* Licensed single-node space: 20 TiB. Usable space: 20 / 1.13 = 17.70 TiB
* Licensed HA pair space: 20 TiB. Usable space: 20 / 2.67 = 7.48 TiB

You need to calculate the licensed capacity and the usable space to ensure you have enough capacity for your deployment.

[cols="25,30,45",options="header"]
|===
| Description | Single node | HA pair

| Usable space
| 20 TiB
| 10 TiB per node

20 TiB for HA pair

| Licensed space
| 23 TiB 

(20 x 1.13 = 22.6, round up to next full TiB)
| 54 TiB 

(20 x 2.67 = 53.4, round up to next full TiB)


| Maximum usable space per node
|  353 TiB 

(400 / 1.13)
a| Per node in a HA pair:

* 74 TiB [(400 / 2) / 2.67]

Per HA pair in a multi-node cluster:

* Two-node: 148 TiB (2 x 74)
* Four-node: 296 TiB (4 x 74)
* Six-node: 444 TiB (6 x 74)
* Eight-node: 592 TiB (8 x 74)
|===
