---
sidebar: sidebar
permalink: concept_adm_upgrading_nodes.html
keywords: administer, administering, web, upgrading nodes
summary: After you deploy an ONTAP Select cluster, you can upgrade the ONTAP image of each node as needed using the standard ONTAP software upgrade procedure.
---

= Upgrading the ONTAP Select nodes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After deploying an ONTAP Select cluster, you can upgrade the ONTAP image at each node in the cluster as needed.

[CAUTION]
You cannot use the Deploy administration utility to perform upgrades of existing ONTAP Select nodes. The Deploy utility can only be used to create new ONTAP Select clusters.

== General procedure

At a high level, you should use the following steps to upgrade an existing ONTAP Select node:

. Navigate to downloads page at the NetApp support site.
+
https://mysupport.netapp.com/site/downloads[NetApp Support Downloads^]

. Click *ONTAP Select Node Upgrade*.

. Select and download the appropriate upgrade version responding to all prompts as needed.

. Review the Release Notes for additional information and any required procedures before upgrading an ONTAP Select node. You can access the Release Notes for your version of ONTAP Select at the product library page.
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62293[ONTAP Select product library^]

. Upgrade the ONTAP Select node using the ONTAP upgrade procedures and the ONTAP Select upgrade file.
+
https://docs.netapp.com/us-en/ontap/[ONTAP 9 documentation^]

== Reverting an ONTAP Select node

You cannot revert an ONTAP Select node to a version prior to the version that was originally installed. For example:

ONTAP Select 9.4 is initially installed::
You can upgrade the node to version 9.5 and then revert back to version 9.4 if needed.
ONTAP Select 9.5 is initially installed::
You cannot revert to version 9.4 because this version is prior to the version that was originally installed.

== Using the VMXNET3 network driver

Beginning with ONTAP Select 9.5 using Deploy 2.10, VMXNET3 is the default network driver included with new cluster deployments on VMware ESXi. If you upgrade an existing ONTAP Select node to version 9.5, the network driver is not automatically upgraded. You must manually upgrade to VMXNET3. You should contact NetApp support for assistance with the upgrade.
