---
sidebar: sidebar
permalink: concept_vpi_overview.html
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, overview, functionality
summary: The VMware vCenter plug-in for ONTAP Select Deploy is designed for ONTAP Select administrators working in the VMware environment. It provides an alternative to the native Deploy user interface.
---

= Overview of the Deploy vCenter plug-in
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The VMware vCenter plug-in for ONTAP Select Deploy is designed for ONTAP Select administrators working in the VMware environment. It provides an alternative to the native Deploy user interface.

== Packaged with Deploy

The Deploy vCenter plug-in is packaged with the Deploy administration utility. After using the Deploy user interface to install the plug-in to the vCenter server, you can access the plug-in through the vSphere web interface.

== Integration with VMware

For many businesses, VMware vCenter is a central platform for administering virtualized data center and cloud resources. Because the Deploy plug-in is tightly integrated with vCenter, administrators can quickly move between the ONTAP Select and vCenter domains to leverage the relationships among the various resources.

== Functionality provided by the Deploy vCenter plug-in

After installing the Deploy vCenter plug-in, there are two primary options available through vSphere in the *Global Inventory Lists* pane.

=== ONTAP Select Clusters

The ONTAP Select Clusters option is roughly equivalent to the *Clusters* tab in the native Deploy web user interface. It provides the functionality described in the following table.

[cols="30,70"*,options="header"]
|===
|You perform this operation ...
|By doing this ...

|Deploy an ONTAP Select cluster
|Click New ONTAP Select.

|View cluster details
|Select a cluster, click Summary, and then click Details.

|View cluster event messages
|Select a cluster, click Summary, and then click Events.

|Move a cluster online or offline, or delete a cluster
|Select a cluster, click Actions, and then click the desired action.

|Launch System Manager
|Select a cluster, click Summary, click Details, and then click Launch System Manager.

|View the ESXi hosts used by a cluster
|Select a cluster, click More Objects, and then click Hosts. Select a host for more details and further actions.

|View the ONTAP VMs used by a cluster
|Select a cluster, click More Objects, and then click ONTAP VMs. Select a VM for more details and further actions.

|View the datastores used by a cluster
|Select a cluster, click More Objects, and then click Datastores. Select a datastore for more details and further actions.

|View the networks used by a cluster
|Select a cluster, click More Objects, and then click Networks. Select a network for more details and further actions.

|===

=== ONTAP Select Deploy

The ONTAP Select Deploy option is roughly equivalent to the *Hypervisor Hosts* and *Administration* tabs in the native Deploy web user interface. It provides functionality through three tabs at the top of the page as described in the following table.

[cols="15,85"*,options="header"]
|===
|Tab
|Description

|Summary
|Describes the characteristics of the Deploy instance, including the host name and IP address.

|Host
|Displays information about the ESXi hosts registered with ONTAP Select Deploy. You can add or remove hosts.

|Administration
|Allows you to perform administrative tasks through the Deploy utility. This functionality is equivalent to the ONTAP Select Deploy native user interface, except that the *Credentials* and *Plugins* options are not available with the plug-in.

|===

== Compare the vCenter plug-in to the native Deploy user interface

The functionality provided with the vCenter plug-in through vSphere is equivalent to the native Deploy user interface. However, there are a few features that are not provided with the plug-in and are only available with the Deploy user interface.

=== Manage the vCenter plug-in

You cannot install, update, remove, or verify the vCenter plug-in using the vCenter plug-in. You must perform these management tasks through the native Deploy user interface.

=== Manage vCenter credentials

Before installing the vCenter plug-in, you must add the necessary vCenter credentials to Deploy using the native Deploy user interface.

=== ONTAP Select clusters must be controlled by the same vCenter server

You can only deploy and support the ONTAP Select clusters managed by the single vCenter server where the plug-in is installed. You cannot use the plug-in to access ONTAP Select clusters managed by other vCenter servers or clusters running on standalone ESXi or KVM hosts.
