---
sidebar: sidebar
permalink: concept_usecase_overview.html
keywords: ontap select, business use case overview, deployment, storage, development and testing
summary: ONTAP Select is suitable for several different types of applications based on the inherent flexibility provided through the hypervisor virtualization.
---

= Business needs and usage scenarios
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
ONTAP Select is suitable for several different types of applications based on the inherent flexibility provided through the hypervisor virtualization.

== Deployment

From a high level, you can deploy ONTAP Select in two different ways regarding the workload on the hypervisor host servers.

=== Dedicated deployment
With the dedicated deployment model, a single instance of ONTAP Select runs on the host server. No other significant processing runs on the same hypervisor host.

=== Collocated deployment
With the collocated deployment model, ONTAP Select shares the host with other workloads. Specifically, there are additional virtual machines, each typically running computational applications. These compute workloads are local to the ONTAP Select cluster. This model supports specialized application and deployment requirements. As with the dedicated deployment model, each ONTAP Select virtual machine must run on a separate and dedicated hypervisor host.

== Storage

ONTAP Select can be used as primary or secondary storage, depending on your business needs.

=== Primary storage

In certain cases, you may choose to deploy ONTAP Select as your primary storage platform. These types of implementations vary and depend on the workload characteristics of the applications as well as your business objectives.

=== Disaster recovery and secondary storage

You can use ONTAP Select to implement additional storage that augments your primary storage capabilities. The additional storage can be used to support your organization’s disaster recovery efforts and data backup plans.

== Development and testing

As you deploy various applications within your organization, you can use ONTAP Select as an integral part of the overall application development and testing process. For example, you may need temporary storage to hold test input or output data. The length of these types of deployments can vary based on the application characteristics and requirements.
