---
sidebar: sidebar
permalink: concept_lic_cp_operation.html
keywords: license, licensing, Capacity Pools, operation details
summary: The Capacity Pools licensing model is different from the Capacity Tiers model. Instead of a dedicating storage capacity to each individual node, the storage capacity is allocated to a pool and shared among many nodes. Additional components and processes have been created to support the Capacity Pools model.
---
= Operational details for ONTAP Select Capacity Pools licensing model
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Capacity Pools licensing model is different from the Capacity Tiers model. Instead of a dedicating storage capacity to each individual node, the storage capacity is allocated to a pool and shared among many nodes. Additional components and processes have been created to support the Capacity Pools model.

== License Manager

The License Manager runs as a separate process within each instance of the Deploy administration utility. Some of the functions provided by LM include:

* Generate a unique twenty-digit serial number for each node based on the Capacity Pool license serial number
* Create leases for capacity from the shared Capacity Pools based on requests from the ONTAP Select nodes
* Report pool usage information through the Deploy user interface

== Lease characteristics

The storage allocated for every data aggregate at a node using a Capacity Pool license must have an associated lease. The node requests a storage lease and if the capacity is available, the License Manager responds with a lease. Each lease has the following explicit or implicit attributes:

* License Manager
Every ONTAP Select node is associated with one License Manager instance
* Capacity Pool
Every ONTAP Select node is associated with one Capacity Pool
* Storage allocation
A specific capacity value is assigned in the lease
* Expiration date and time
Leases have a duration of between one hour and seven days depending on the user configuration.

== License Lock ID

Each instance of the License Manager, and therefore each corresponding Deploy utility instance, is identified with a unique 128-bit number. This number is combined with the nine-digit Capacity Pool license serial number to lock the pool to a specific License Manager instance (which is effectively a Deploy instance). You must provide both values at the NetApp support site as part of generating the NetApp License File (NLF).

You can determine the License Lock ID for your Deploy instance using the web user interface in the following ways:

* Getting Started page
This page is displayed when you first sign in to Deploy. You can also display the page by clicking the drop down box at the top right of the page and selecting Getting Started. The LLID is displayed in the Add Licenses section.
* Administration
Click the *Administration* tab a the top of the page, then click *Systems* and *Settings*.

== Basic lease operations

An ONTAP Select node must locate or request a valid capacity lease every time a data aggregate is created, expanded, or changed. A lease obtained from a previous request that is still valid can be used, or a new lease can be requested if needed. The following steps are taken by the ONTAP Select node to locate a Capacity Pool lease:

. If an existing lease is located at the node, it is used as long as all of the following are true:
* Lease has not expired
* Storage request for the aggregate does not exceed the lease capacity

. If an existing lease cannot be located, the node requests a new lease from the License Manager.

== Return storage capacity to a Capacity Pool
Storage capacity is allocated from a Capacity Pool as needed and each new request can reduce the available storage in the pool. Storage capacity is returned to the pool in several situations, including:

* Lease for a data aggregate expires and is not renewed by the node
* Data aggregate is deleted

[NOTE]
If an ONTAP Select virtual machine is deleted, any active leases remain in effect until they expire. When this occurs, the capacity is returned to the pool.

== Determine capacity for Capacity Pools license

The licensed capacity for a Capacity Pool license is in full TiB amounts, with a minimum of 2 TiB. You calculate the licensed capacity by multiplying the amount of usable space by the overhead factor. The overhead factor differs between a single-node and multi-node (HA-pair based) clusters:

* Overhead factor for single-node clusters is 1.13
* Overhead factor for multi-node clusters is 2.67

You need to calculate the licensed capacity to ensure you have enough for your deployment.

[cols="25,30,45",options="header"]
|===
| Description | Single node | HA pair

| Usable space
| 20 TiB
| 10 TiB per node

20 TiB for HA pair

| Licensed space
| 23 TiB 

(20 x 1.13 = 22.6, round up to next full TiB)
| 54 TiB 

(20 x 2.67 = 53.4, round up to next full TiB)


| Maximum usable space per node
|  353 TiB 

(400 / 1.13)
a| Per node in a HA pair:

* 74 TiB [(400 / 2) / 2.67]

Per HA pair in a multi-node cluster:

* Two-node: 148 TiB (2 x 74)
* Four-node: 296 TiB (4 x 74)
* Six-node: 444 TiB (6 x 74)
* Eight-node: 592 TiB (8 x 74)
|===

// 2023-10-17, Removed mention of old OTS versions