---
sidebar: sidebar
permalink: concept_vpi_manage_before.html
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, manage, managing
summary: There are several things you need to do before installing and managing the Deploy vCenter plug-in.
---

= Before you begin
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several things you need to do before installing and managing the Deploy vCenter plug-in.

== Decide whether to use the Deploy web user interface or the CLI

In most situations, the Deploy web user interface provides the most convenient option when managing the vCenter plug-in, and this is the option described in this procedure. However, you can also manage the plug-in using the Deploy command line interface. For more information, type the following commands at the Deploy CLI prompt:

* `deploy plugin ?` (Subcommands include: install, remove, show, and update)
* `deploy plugin-packages show`

== Preparation common to all management tasks

There are several steps you must take regardless of the management task. The common preparation includes:

* Reading the section Getting started to become familiar with the Deploy vCenter plug-in.
* Assuring that the ONTAP Select Deploy administration utility is installed and running.
See the Installation and Cluster Deployment documentation for VMware for more information.
* Acquiring the account credentials:
** Deploy administrator account
** vCenter server accounts
* Assuring that the Deploy utility has network access to port 443 at the vCenter server.

Additional preparation might be required depending on the management task.

== Prepare the vCenter server accounts

Before installing and using the Deploy plug-in, you must create the vCenter accounts with the
required privileges. You can create a single account with all the necessary privileges or create
multiple accounts each with a single privilege. For simplicity, the following example distributes
the vCenter privileges across three separate roles that can then be assigned to the three
corresponding accounts.

=== Validate end user access to the plug-in

You need an account to validate access to the plug-in through vSphere. The account must have the following vCenter privilege: sessions.validate.session. After the account is created in vCenter, you must define it to the Deploy administration utility. In the Deploy web user interface, click the Administration tab and then Credentials to provide the vCenter server location and credentials.

This account is used in the following ways:

* The named vCenter server becomes available as an installation target in the plug-in registration dialog window.
* The account is used by Deploy to validate vSphere user requests to access the plug-in after the plug-in has been installed.

=== Manage the plug-in

In the Deploy web user interface, you can install the plug-in and then upgrade or remove it. Each time you perform one of these management actions, you are prompted for a vCenter account in the popup window. Each of the management actions is controlled through a separate vCenter privilege.

To install, upgrade, and remove the plug-in, you must assign the following privileges:

* Extension
** Register extension
** Update extension
** Unregister extension

You can create a single role and account with all three privileges or divide the privileges among multiple accounts as needed.

=== Access the plug-in

End users can access the plug-in through vSphere. You must assign the following privilege to the accounts that will use the plug-in:

* NetApp
** ONTAP Select Deploy
*** Administrator
