---
sidebar: sidebar
permalink: concept_vpi_vcenter_integration.html
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, vcenter integration
summary: The Deploy plug-in is tightly integrated with the vCenter server. Because of this integration, you can easily navigate among the resources managed by the Deploy utility and vCenter server. Several examples of this integration are provided below.
---

= Deploy plug-in and vCenter integration
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Deploy plug-in is tightly integrated with the vCenter server. Because of this integration, you can easily navigate among the resources managed by the Deploy utility and vCenter server. Several examples of this integration are provided below.

== VMware resources assigned to an ONTAP Select cluster

An ONTAP Select cluster runs on VMWare as a set of one or more nodes. Each node is a dedicated virtual machine on a different ESXi host. An ONTAP Select cluster is associated with the following VMware resources:

* Hosts
* ONTAP VMs
* Datastores
* Networks

There are several ways to view the VMware resources used by a specific ONTAP Select cluster.

== View the VMware resources for a cluster through the plug-in

You can view the VMware resources assigned to an ONTAP Select cluster through the Deploy plug-in.

.Steps

. Sign in to the vCenter server through vSphere HTML5 using a browser.

. Click *ONTAP Select Clusters* in the *Global Inventory Lists* pane.

. Click the desired cluster in the list on the right.

. Click the *More Objects* tab and select the desired resource category at the top of the page.

. Select a specific VMware resource to display additional information.

== View the ONTAP Select clusters through an ESXi virtual machine

You can view the ONTAP Select cluster and associated cluster resources by accessing a VMware virtual machine.

.Steps

. Sign in to the vCenter server through vSphere HTML5 using a browser.

. Click *Menu* at the top and then click *VMs and Templates*.

. Select the desired virtual machine in the list on the left.

. Click the *More Objects* tab to view the ONTAP Select cluster running in the VM.

. To see the entire collection of VMware resources associated with the cluster, click the ONTAP Select cluster and then click the *More Objects* tab.

== Create a single-node cluster on an ESXI host

You can select an ESXI hypervisor host through the vSphere interface and deploy an ONTAP Select single-node cluster.

.Steps

. Sign in to the vCenter server through vSphere HTML5 using a browser.

. Click *Menu* at the top and then click *Hosts and Clusters*.

. Right click the desired hypervisor host on the left, select *ONTAP Select*, and then click *New ONTAP Select*.

. Complete the deployment process by following the steps in link:task_deploy_cluster.html[Deploy an ONTAP Select cluster].
