---
sidebar: sidebar
permalink: concept_lic_cp_serial_number.html
keywords: license, licensing, capacity pools, node serial numbers
summary: With the capacity tiers licensing model, the nine-digit node serial number is the same as the license serial number assigned to the node. However, the serial numbers assigned to nodes using the capacity pools licensing model have a different format.
---

= Node serial numbers
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
With the capacity tiers licensing model, the nine-digit node serial number is the same as the license serial number assigned to the node. However, the serial numbers assigned to nodes using the capacity pools licensing model have a different format.

The serial number of a node using capacity pools licensing has the following format:

`999 ppppppppp nnnnnnnn`

[NOTE]
Spaces have been added for clarity, but are not part of the actual serial number.

Each section of the node serial number is described in the following table, from left to right.

[cols="15,85"*,options="header"]
|===
|Section
|Description

|'999'
|Constant three-digit value reserved by NetApp.

|ppppppppp
|Variable nine-digit license serial number assigned to the capacity pool by NetApp

|nnnnnnnn
|Variable eight-digit value generated by the License Manager for each node using the capacity pool

|===

[NOTE]
Attention: When opening a case with NetApp support involving a node that uses a capacity pool license, you cannot provide the full twenty-digit node serial number. Instead, you must provide the nine-digit capacity pool license serial number. You can derive the license serial number from the node serial number as shown above. Skip the first three digits of the node serial number ('999') and extract the next nine digits (ppppppppp).
