---
sidebar: sidebar
permalink: concept_terminology.html
keywords: terminology, key concepts, concepts
summary: As you begin to explore ONTAP Select and plan a deployment, it is helpful to first become familiar with the terminology and key concepts.
---

= Terminology and key concepts
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
As you begin to explore ONTAP Select and plan a deployment, it is helpful to first become familiar with the terminology and key concepts.

ONTAP Select Deploy::
ONTAP Select Deploy is the administration utility that you use to deploy ONTAP Select clusters. The Deploy utility runs in a dedicated Linux virtual machine. You can access the Deploy utility through the web user interface, CLI management shell, and REST API.

Kernel-based Virtual Machine::
Kernel-based Virtual Machine (KVM) is a virtualization feature of the Linux kernel, which allows it to act as a hypervisor platform. A wide range of guest operating systems are supported.

Hypervisor host versus ONTAP Select node::
A _hypervisor host_ is the core hardware platform that hosts an ONTAP Select virtual machine. When an ONTAP Select virtual machine is deployed and active on a hypervisor host, it is considered to be an _ONTAP Select node_.

ONTAP Select cluster::
You can create an _ONTAP Select cluster_ composed of one, two, four, six, or eight nodes. Multi-node clusters always contain one or more HA pairs. For example, a four-node cluster consists of two HA pairs. A single node cluster does not provide HA capability.

Preparation of the hypervisor host environment::
Before using the Deploy administration utility to deploy an ONTAP Select cluster, you need to prepare the hypervisor hosts where ONTAP Select will run, including the storage and networking environments. This host pre-configuration is done outside of the ONTAP Select product based on the current requirements and limitations.

Evaluation versus production deployments::
Every ONTAP Select node runs with either an _evaluation license_ or a _purchased license_. An evaluation license allows you to evaluate ONTAP Select prior to deploying it in a production environment. The evaluation license is automatically generated and applied. If you deploy a cluster in a production environment, you must purchase a license which involves choosing:

* Licensing model
* Storage capacity
* Platform license offering

Capacity tiers licensing model::
The capacity tiers licensing model is the original option when licensing storage for an ONTAP Select deployment. It is based on the ONTAP model used with NetApp AFF and FAS. A separate license is required for each node. The storage capacity is locked to the node and perpetual (no renewal required).

Capacity pools licensing model::
The capacity pools licensing model was introduced with ONTAP Select 9.5 using Deploy 2.10. A separate license is required for each storage capacity pool. The capacity pool license is locked to a License Manager instance (that is a Deploy instance) and must be renewed based on the terms of your purchase. You can license and use any number of capacity pools in your organization. However, because the capacity pools are shared by the ONTAP Select nodes, fewer licenses are typically required than capacity tiers licensing.

License Manager::
The License Manager is a software component which supports capacity pools licensing. It is currently part of the Deploy administration utility. LM leases storage to the ONTAP Select nodes from the shared pools it manages. The _License Lock ID_ is a numeric string uniquely identifying each LM instance, and therefore each Deploy instance. You must use both the capacity pool license serial number and LLID to generate a license file.

Platform license offerings::
There are three license offerings available which determine the size capabilities of the ONTAP Select virtual machine when you purchase a license:

* Standard
* Premium
* Premium XL

For more information, see the two sections _Plan_ and _License_.

Storage pools versus datastores::
An ONTAP Select _storage pool_ is a logical data container designed to abstract and hide the underlying physical storage. A storage pool is hypervisor-independent. When deployed on an ESXi hypervisor host, the ONTAP Select storage pool is synonymous with the VMware _datastore_.

Cluster MTU::
Cluster MTU is a feature allowing you to configure the MTU size used on the internal network used with an ONTAP Select multi-node cluster. The Deploy administration utility adjusts the MTU size as you configure the HA pairs to accommodate your networking environment. You can also manually set the value.

ONTAP Select vNAS::
The ONTAP Select vNAS solution allows an ONTAP Select node to access VMware datastores on external storage. With ONTAP Select vNAS, a local RAID controller is no longer needed; the RAID functionality is assumed to be provided by the remote storage. ONTAP Select vNAS can be configured in the following ways:

* VMware vSAN
* Generic external storage array

In both cases, the external storage must be configured prior to creating an ONTAP Select cluster or expanding the storage capacity of an existing node.

Node re-hosting on the ESXi VM::
When you deploy a cluster that uses external storage available through the ONTAP Select vNAS solution (either VMware vSAN or a generic external storage array), the ESXi virtual machine hosting the ONTAP Select node can be moved through actions utilizing the following VMware features:

* vMotion
* High Availability (HA)
* Distributed Resource Scheduler (DRS)
+
The ONTAP Select Deploy utility detects the movement of the virtual machine as part of executing an operation on the cluster, such as:
+
* cluster online
* cluster offline
* storage add
+
When a virtual machine is moved, the Deploy utility updates its internal database and configures the new ESXi host. All actions performed on the ONTAP Select node are blocked until the movement of the virtual machine and Deploy updates are completed.

Open vSwitch for KVM::
Open vSwitch (OVS) is a software implementation of a virtual switch supporting multiple networking protocols. OVS is open source and available according to the Apache License 2.0.

Mediator service::
The ONTAP Select Deploy utility includes a mediator service which connects to the nodes in the active two-node clusters. This service monitors each HA pair and assists in managing failures.

[CAUTION]
If you have one or more active two-node clusters, the ONTAP Select Deploy virtual machine administering the clusters must be running at all times. If the Deploy virtual machine is halted, the mediator service is unavailable and HA capability is lost for the two-node clusters.

MetroCluster SDS::
MetroCluster SDS is a feature that provides an additional configuration option when deploying a two-node ONTAP Select cluster. Unlike a typical two-node ROBO deployment, the MetroCluster SDS nodes can be separated by a much greater distance. This physical separation enables additional use cases, such as disaster recovery. You must have a premium license or higher to use MetroCluster SDS. In addition, the network between the nodes must support a minimum latency requirement.

Credential store::
The Deploy credential store is a secure database holding account credentials. It is used primarily to register hypervisor hosts as part of creating a new cluster. See the _Plan_ section for more information.

Storage efficiency::
ONTAP Select provides storage efficiency options that are similar to the storage efficiency options present on FAS and AFF arrays. Conceptually, ONTAP Select with direct-attached storage (DAS) SSDs (using a premium license) is similar to an AFF array. Configurations using DAS with HDDs and all vNAS configurations should be considered similar to a FAS array. The main difference between the two configurations is that ONTAP Select with DAS SSDs supports inline aggregate level deduplication and aggregate level background deduplication. The remaining storage efficiency options are available for both configurations.
+
The vNAS default configurations enable a write optimization feature known as single instance data logging (SIDL). With ONTAP Select 9.6 and later releases, the background ONTAP storage efficiency features are qualified with SIDL enabled. See the _Deep dive_ section for more information.

Cluster refresh::
After creating a cluster, you can make changes to the cluster or virtual machine configuration outside of the Deploy utility using ONTAP or hypervisor administration tools. You can also migrate a virtual machine which causes configuration changes. When these changes occur, the Deploy utility is not automatically updated and can become out of sync with the state of the cluster. You can use the cluster refresh feature to update the Deploy configuration database. Cluster refresh is available through the Deploy web user interface, CLI management shell, and REST API.

Software RAID::
When using direct-attached storage (DAS), RAID functionality is traditionally provided through a local hardware RAID controller. You can instead configure a node to use _software RAID_ where the ONTAP Select node provides the RAID functionality. If you use software RAID, a hardware RAID controller is no longer needed.

ONTAP Select image install::
Beginning with ONTAP Select Deploy 2.8, the Deploy administration utility contains only a single version of ONTAP Select. The version included is the most current available at the time of release. The ONTAP Select image install feature allows you to add earlier versions of ONTAP Select to your instance of the Deploy utility, which can then be used when deploying an ONTAP Select cluster. See link:task_cli_deploy_image_add.html[Add ONTAP Select images for more information].

[NOTE]
You should only add an ONTAP Select image with a version that is earlier than the original version included with your instance of Deploy. Adding later versions of ONTAP Select without also updating Deploy is not supported.

Administering an ONTAP Select cluster after it is deployed::
After you deploy an ONTAP Select cluster, you can configure the cluster as you would a hardware-based ONTAP cluster. For example, you can configure an ONTAP Select cluster using System Manager or the standard ONTAP command line interface.

.Related information

link:task_cli_deploy_image_add.html[Add an ONTAP Select image to Deploy]

// 2023-09-25, ONTAPDOC-1204
// 2023-10-17, Removed mention of old OTS versions