---
sidebar: sidebar
permalink: concept_adm_upgrading_nodes.html
keywords: administer, administering, web, upgrading nodes
summary: After you deploy an ONTAP Select cluster, you can upgrade the ONTAP image of each node as needed using the standard ONTAP software upgrade procedure.
---
= Upgrade the ONTAP Select nodes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After deploying an ONTAP Select cluster, you can upgrade the ONTAP image at each node in the cluster as needed.

[CAUTION]
You cannot use the Deploy administration utility to perform upgrades of existing ONTAP Select nodes. The Deploy utility can only be used to create new ONTAP Select clusters.

== General procedure

At a high level, you should use the following steps to upgrade an existing ONTAP Select node.

.Steps

. Access the link:https://mysupport.netapp.com/site/downloads/[NetApp Support Site downloads^] page.

. Scroll down and select *ONTAP Select Image*.

. Select the desired release of the install image.

. Review the End User License Agreement (EULA) and select *Accept & Continue*.

. Select and download the appropriate *ONTAP Select Image Upgrade* package. Respond to all prompts as needed.
+
Review the link:reference_release_notes.html[release notes] for additional information and any required procedures before upgrading an ONTAP Select node.

. Upgrade the ONTAP Select node using the standard ONTAP upgrade procedures with the ONTAP Select upgrade file. For information on supported upgrade paths, see the link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html[Supported ONTAP upgrade paths^].

== Revert an ONTAP Select node

You cannot revert an ONTAP Select node to a version prior to the one on which it was originally installed. For example:

ONTAP Select 9.16.1 is initially installed::
You can upgrade the node to version 9.17.1 and then revert back to version 9.16.1 if needed.

ONTAP Select 9.17.1 is initially installed::
Reversion is not possible because there was no earlier version previously installed.

== Use the VMXNET3 network driver

VMXNET3 is the default network driver included with new cluster deployments on VMware ESXi. If you upgrade an existing ONTAP Select node running ONTAP Select 9.4 or earlier, the network driver is not automatically upgraded. You must manually upgrade to VMXNET3. You should contact NetApp support for assistance with the upgrade.

.Related information

link:https://docs.netapp.com/us-en/ontap/upgrade/index.html[ONTAP upgrade overview^]

// 2023-Oct-17, prep for repo version split
// 2023-Nov-13, GitHub issue #222
// 2024-Mar-26, GitHub issue #244
// 2024-Apr-04, GitHub issue #244