---
sidebar: sidebar
permalink: concept_stor_eff_support.html
keywords: ontap select, storage efficiency support
summary: ONTAP Select provides storage efficiency options that are similar to the storage efficiency options present on FAS and AFF arrays.
---

= Storage efficiency support
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
ONTAP Select provides storage efficiency options that are similar to the storage efficiency options present on FAS and AFF arrays.

ONTAP Select virtual NAS (vNAS) deployments using all-flash VSAN or generic flash arrays should follow the best practices for ONTAP Select with non-SSD direct-attached storage (DAS).

An AFF-like personality is automatically enabled on new installations as long as you have DAS storage with SSD drives and a premium license.

With an AFF-like personality, the following inline SE features are automatically enabled during installation:

* Inline zero pattern detection
* Volume inline deduplication
* Volume background deduplication
* Adaptive inline compression
* Inline data compaction
* Aggregate inline deduplication
* Aggregate background deduplication

To verify that ONTAP Select has enabled all the default storage efficiency policies, run the following command on a newly created volume:

----
<system name>::> set diag
Warning: These diagnostic commands are for use by NetApp personnel only.
Do you want to continue? {y|n}: y
twonode95IP15::*> sis config
Vserver:                                SVM1
Volume:                                 _export1_NFS_volume
Schedule                                -
Policy:                                 auto
Compression:                            true
Inline Compression:                     true
Compression Type:                       adaptive
Application IO Si                       8K
Compression Algorithm:                  lzopro
Inline Dedupe:                          true
Data Compaction:                        true
Cross Volume Inline Deduplication:      true
Cross Volume Background Deduplication:  true
----

[NOTE]
For ONTAP Select upgrades from 9.6 and later, you must install ONTAP Select on DAS SSD storage with a premium license. In addition, you must check the *Enable Storage Efficiencies* check box during the initial cluster installation with ONTAP Deploy. Enabling an AFF-like personality post-ONTAP upgrade when prior conditions have not been met requires the manual creation of a boot argument and a node reboot. Contact technical support for further details.

.ONTAP Select storage efficiency configurations

The following table summarizes the various storage efficiency options available, enabled by default, or not enabled by default but recommended, depending on the media type and software license.

[cols=4,options="header"]
|===
| ONTAP Select features | DAS SSD (premium or premium XL^1^)  | DAS HDD (all licenses)  | vNAS (all licenses)
| Inline zero detection
| Yes (default)
| Yes Enabled by user on a per-volume basis
| Yes Enabled by user on a per-volume basis
| Volume inline deduplication
| Yes (default)
| Not available
| Not supported
| 32K inline compression (secondary compression)
| Yes Enabled by user on a per volume basis.
| Yes Enabled by user on a per-volume basis
| Not supported
| 8K inline compression (adaptive compression)
| Yes (default)
| Yes Enabled by user on a per volume basis
| Not supported
| Background compression
| Not supported
| Yes Enabled by user on a per volume basis
| Yes Enabled by user on a per-volume basis
| Compression scanner
| Yes
| Yes
| Yes Enabled by user on a per-volume basis
| Inline data compaction
| Yes (default)
| Yes Enabled by user on a per volume basis
| Not supported
| Compaction scanner
| Yes
| Yes
| Not supported
| Aggregate inline deduplication
| Yes (default)
| N/A
| Not supported
| Volume background deduplication
| Yes (default)
| Yes Enabled by user on a per volume basis
| Yes Enabled by user on a per-volume basis
| Aggregate background deduplication
| Yes (default)
| N/A
| Not supported
|===

[small]#^1^ONTAP Select 9.6 supports a new license (premium XL) and a new VM size (large). However, the large VM is only supported for DAS configurations using software RAID. Hardware RAID and vNAS configurations are not supported with the large ONTAP Select VM in the 9.6 release.#

.Notes on upgrade behavior for DAS SSD configurations

After upgrading to ONTAP Select 9.6 or later, wait for the `system node upgrade-revert show` command to indicate that the upgrade has completed before verifying the storage efficiency values for existing volumes.

On a system upgraded to ONTAP Select 9.6 or later, a new volume created on an existing aggregate or a newly created aggregate has the same behavior as a volume created on a fresh deployment. Existing volumes that undergo the ONTAP Select code upgrade have most of the same storage efficiency policies as a newly created volume with some variations:

Scenario 1::
If no storage efficiency policies were enabled on a volume prior to the upgrade, then:
+
* Volumes with `space guarantee = volume` do not have inline data-compaction, aggregate inline deduplication, and aggregate background deduplication enabled. These options can be enabled post-upgrade.
* Volumes with `space guarantee = none` do not have background compression enabled. This option can be enabled post upgrade.
* Storage efficiency policy on the existing volumes is set to auto after upgrade.

Scenario 2::
If some storage efficiencies are already enabled on a volume prior to the upgrade, then:
+
* Volumes with `space guarantee = volume` do not see any difference after upgrade.
* Volumes with `space guarantee = none` have aggregate background deduplication turned on.
* Volumes with `storage policy inline-only` have their policy set to auto.
* Volumes with user defined storage efficiency policies have no change in policy, with the exception of volumes with `space guarantee = none`. These volumes have aggregate background deduplication enabled.

// 2023-10-17, Removed mention of old OTS versions