---
sidebar: sidebar
permalink: concept_lic_platforms.html
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl
summary: You can purchase an ONTAP Select Capacity Tier or Capacity Pool license in one of three platform capacity levels. These license offerings determine the capabilities of the hosts where you deploy ONTAP Select.
---
= Understand the platform license offerings for ONTAP Select
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can purchase an ONTAP Select Capacity Tier or Capacity Pool license in one of three platform capacity levels. These license offerings determine the capabilities of the hosts where you deploy ONTAP Select.

== What a platform license offering provides

A specific license offering defines and restrictions the capabilities of the hypervisor host in two areas:

* Instance type (CPU, memory)
* Additional features

The license offerings are arranged in an ascending order of capabilities from standard to premium XL. In general, the license option you choose grants you the capabilities of that level and all lower levels. For example, the premium level provides the capabilities of both premium and standard.

== Platform license offerings

There are three platform license offerings available.

=== Standard

The standard offering provides the following capabilities:

* Small instance type only
* Hard disk drives (HDD) only
* Local hardware RAID controller only
* vNAS

=== Premium

The premium offering provides the following capabilities:

* Small or medium instance type
* Hard disk drives (HDD) or Solid state drives (SSD)
* Local hardware RAID controller or software RAID
* vNAS
* MetroCluster SDS

=== Premium XL

The premium XL offering provides the following capabilities:

* Small, medium, or large instance type
* HDDs, SSDs, or NVMe drives
* Local hardware RAID controller or software RAID
* vNAS
* MetroCluster SDS

[NOTE]
Use of the large instance type or NVMe drives in an SW-RAID configuration isn't supported on Kernel-Based Virtual Machine (KVM).

== Compare hardware support for platform license offerings
The standard, premium, and premium XL license offerings support a wide range of hardware. For up-to-date information on hardware and software versions, see the link:https://mysupport.netapp.com/matrix/[Interoperability Matrix Tool^]. 

|===

2+h|Core item 3+h| Standard, Premium, and Premium XL

2+| Host protocols 
3+| NFS, SMB/CIFS, iSCSI, and NVMe over TCP
2+| Deployment options
3+| Single node

Two-node cluster (HA pair)

Four-, six-, or eight-node cluster
2+| Supported capacity (per node)
3+| Up to 400TB raw data (ESXi and KVM)

2+h|Hardware h| Standard h|Premium h| Premium XL
2+| CPU family 
| Intel Xeon E5-26xx v3 (Haswell) or later	
| Intel Xeon E5-26xx v3 (Haswell) or later	
| Intel Xeon E5-26xx v3 (Haswell) or later	
2+| Select CPU / Memory	
| 4 virtual CPUs (vCPUs) / 16GB of RAM	
| 8 vCPUs / 64GB of RAM	
| 16 vCPUs / 128GB of RAM
2+| Host CPU / Memory minimum requirements ^1^	
| 6 cores / 24GB of RAM	
| 10 cores / 72GB of RAM
| 18 cores / 136GB of RAM
2+| Network (per node)
3+| Minimum of two x 1GbE ports for a single node

Minimum of four x 1GbE ports for a two-node cluster (HA pair)

Minimum of two x 10GbE ports for a four-, six-, or eight-node cluster

2+h| Storage types h| Standard h|Premium h| Premium XL
.2+a| Local DAS with hardware RAID controller

| HDD (SAS, NL-SAS, SATA)
| 8 - 60 drives
| 8 - 60 drives
| 8 - 60 drives
| SSD (SAS)
| Not applicable	
| 4 – 60 drives	
| 4 – 60 drives
2+| Local DAS with software RAID
| Not applicable
| 4 – 60 drives (SSD only)
| 4 – 60 drives (SSD only)
2+| External arrays ^2^
3+| Datastores hosted on external arrays are connected through FC, FCoE, iSCSI, and NFS (NFS isn't supported for KVM). These datastores provide high availability and resilience.

2+h| Software 3+h| Standard, Premium, and Premium XL
2+|Hypervisor support (VMware)
3+| VMware vSphere 7.0GA and updates 1, 2, and 3C 

VMware vSphere 8.0GA and updates 1, 2, and 3
2+| Hypervisor support (KVM)
3+| RedHat Enterprise Linux 64-bit (KVM) 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7, and 8.6 

Rocky Linux (KVM) 9 and 8
2+| Management software
3+| NetApp Active IQ Unified Manager management suite

ONTAP Select Deploy Utility

SnapCenter (optional)

|===

^1^ Assumes two cores and 8Gb RAM for the hypervisor.

^2^ External array protocol support reflects networked storage connectivity.
// 2025 FEB 18, ONTAPDOC-2678
// 2023-09-26, ONTAPDOC-1204
// 2023-12-12, ONTAPDOC-1525