---
sidebar: sidebar
permalink: index.html
summary: Welcome to the documentation portal for ONTAP Select.
---

= ONTAP Select documentation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp ONTAP Select is a software-defined storage appliance you can deploy on a variety of commodity hardware servers running the VMware ESXi and KVM hypervisors. It provides the agility you need to build a flexible and scalable private cloud infrastructure.

== Discover what's new

* link:ri_new_ots.html[What's new in ONTAP Select 9.7]

One of the major changes with ONTAP Select 9.7 is the [yellow-background]*Deploy administration utility is no longer assigned a version number*. Deploy now has the same version number as the associated ONTAP Select release. Each update of the Deploy utility within a specific ONTAP Select release is has a unique build number.

== Navigating the product documentation

ONTAP Select 9.7 can be deployed on VMware ESXi or KVM. This site contains the documentation for ONTAP Select 9.7 running on VMware ESXi as well as hypervisor-independent content (such as the Deploy REST API). You can find the documentation for the KVM version of the product and the release notes, as well as prior product releases, at the https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62293[ONTAP Select product library^].

== Getting more information and connecting with peers.

* link:ri_additional_info.html[Where to get help and find more information]
