---
sidebar: sidebar
permalink: index.html
summary: Welcome to the documentation portal for ONTAP Select.
---

= ONTAP Select documentation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp(R) ONTAP(R) Select is a software-defined storage appliance you can deploy on a variety of commodity hardware servers running the VMware ESXi and KVM hypervisors. ONTAP Select complements the suite of mainstream FAS and AFF ONTAP offerings as well as other software-only options such as Cloud Volumes ONTAP.

== Discover what's new

* link:ri_new_ots.html[What's new in ONTAP Select]

== Navigating the product documentation

This is the primary site for the ONTAP Select documentation and describes ONTAP Select running on VMware ESXi. You can find the documentation for the KVM version of the product as well as the release notes at the https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62293[ONTAP Select product library,window=_blank].

== Connect with peers, get help, and find more information

* https://www.netapp.com/us/documentation/ontap-select.aspx[NetApp ONTAP Select Resources,window=_blank]
* http://community.netapp.com/t5/forums/filteredbylabelpage/board-id/data-ontap-discussions/label-name/ontap%20select[NetApp Community: ONTAP Select,window=_blank]
* link:ri_additional_info.html[Where to get help and find more information,window=_blank]
