---
sidebar: sidebar
permalink: index.html
summary: Welcome to the documentation portal for ONTAP Select.
---

= ONTAP Select documentation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp ONTAP Select is a software-defined storage appliance you can deploy on a variety of commodity hardware servers running the VMware ESXi and KVM hypervisors. It provides the agility you need to build a flexible and scalable private cloud infrastructure.

== Discover what's new

* link:reference_new_ots.html[What's new in ONTAP Select 9.9.1]

One of the major changes beginning with ONTAP Select 9.7 is the [blue]*Deploy administration utility is no longer assigned a version number*. Deploy now has the same version number as the associated ONTAP Select release. However, each update of the Deploy utility within a specific ONTAP Select release has a unique build number.

== Navigate the product documentation

ONTAP Select 9.9.1 can be deployed on VMware ESXi or KVM. This site contains the documentation for ONTAP Select 9.9.1, 9.8, and 9.7 running on VMware ESXi as well as the hypervisor-independent documentation (such as the REST API).

You can find the documentation for the KVM version of the product and the release notes, as well as prior product releases, at the https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62293[ONTAP Select product library^].

== Get more information and connect with peers

* link:reference_additional_info.html[Where to get help and find more information]
