---
sidebar: sidebar
permalink: index.html
summary: Welcome to the documentation portal for ONTAP Select.
---

= ONTAP Select documentation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp ONTAP Select is a software-defined storage appliance you can deploy on a variety of commodity hardware servers running the VMware ESXi or KVM hypervisor. It provides the agility you need to build a flexible and scalable private cloud infrastructure.

== Discover what's new

* link:reference_new_ots.html[What's new in this release]

[NOTE]
====
Beginning with ONTAP Select 9.14.1, support for KVM hypervisor has been reinstated. Previously, support for deploying a new cluster on a KVM hypervisor was removed in ONTAP Select 9.10.1 and support for managing existing KVM cluster and hosts, except to take offline or delete, was removed in ONTAP Select 9.11.1.
====

== Navigate the product documentation

ONTAP Select 9.14.1 can be deployed on VMware ESXi or KVM hypervisor. This site contains the documentation for ONTAP Select 9.14.1, 9.13.1, 9.12.1, 9.11.1, 9.10.1, 9.9.1, 9.8, and 9.7 running on VMware ESXi as well as the hypervisor-independent documentation (such as the REST API).

You can find the release notes as well as documentation for prior releases at the https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62293[ONTAP Select product library^].

== Get more information and connect with peers

* link:reference_additional_info.html[Where to get help and find more information]

// 2023-09-25, ONTAPDOC-1204