---
settings:
  name: ONTAP Select
  harmony_integration: maestro
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  versions:
    - version-number: "9.18.1"
      url: /ontap-select
    - version-number: "9.17.1"
      url: /ontap-select-9171
    - version-number: "9.16.1"
      url: /ontap-select-9161
    - version-number: "9.15.1"
      url: /ontap-select-9151 
    - version-number: "9.14.1"
      url: /ontap-select-9141                    
sidebar:
  entries:
    - title: ONTAP Select 9.18.1 docs
      url: /index.html
    - title: Release Notes
      entries:
        - title: ONTAP Select Release Notes
          url: /reference_release_notes.html
        - title: What's new
          url: /reference_new_ots.html
    - title: Concepts
      entries:
        - title: Learn about ONTAP Select
          url: /concept_ots_overview.html
        - title: ONTAP Select Deploy
          url: /concept_ots_deploy.html
        - title: Business use cases
          entries:
            - title: Business needs and usage scenarios
              url: /concept_usecase_overview.html
            - title: Remote and branch office
              url: /concept_usecase_robo.html
            - title: Private cloud and data center
              url: /concept_usecase_private_cloud.html
            - title: Data protection and efficiency
              url: /concept-data-protection-and-efficiency.html
        - title: Terminology
          url: /concept_terminology.html
    - title: Plan
      entries:
        - title: Deployment workflow
          url: /concept_workflow_deploy.html
        - title: ONTAP Select
          entries:
            - title: General requirements
              url: /reference_plan_ots_general.html
            - title: Hypervisor and hardware
              url: /reference_plan_ots_hardware.html
            - title: Storage and RAID
              url: /reference_plan_ots_storage.html
            - title: External storage requirements
              entries:
                - title: VMware ESXi 
                  url: /reference_plan_ots_vnas.html
                - title: KVM
                  url: /reference_plan_ots_kvm.html
            - title: Networking
              url: /reference_plan_ots_networking.html
            - title: Two-node clusters
              url: /reference_plan_ots_two_node.html
            - title: Remote and branch offices
              url: /reference_plan_ots_robo.html
            - title: MetroCluster SDS
              url: /reference_plan_ots_mcc_sds.html
            - title: VMware vCenter on ESXi
              url: /reference_plan_ots_vcenter.html
        - title: ONTAP Select Deploy
          entries:
            - title: General requirements
              url: /reference_plan_dep_general.html
            - title: VMware environment
              url: /reference_plan_dep_vmware.html
        - title: Best practices
          url: /reference_plan_best_practices.html
    - title: License
      entries:
        - title: Options
          entries:
            - title: Learn about evaluation licenses
              url: /concept_lic_evaluation.html
            - title: Production licenses
              url: /concept_lic_production.html
            - title: Platform license offerings
              url: /concept_lic_platforms.html
        - title: Capacity Pools licensing model
          entries:
            - title: Operational details
              url: /concept_lic_cp_operation.html
            - title: Node serial numbers
              url: /concept_lic_cp_serial_number.html
            - title: Restrictions
              url: /concept_lic_cp_restrictions.html
            - title: Capacity Pools versus Capacity Tiers
              url: /concept_lic_cp_compare_ct.html
            - title: Summary of benefits
              url: /concept_lic_cp_benefits.html
        - title: Purchase
          entries:
            - title: Licensing workflow
              url: /concept_lic_workflow.html
            - title: Capacity Tiers
              url: /task_lic_acquire_ct.html
            - title: Capacity Pools
              url: /task_lic_acquire_cp.html
        - title: ONTAP features
          url: /reference_lic_ontap_features.html
    - title: Install
      entries:
        - title: Pre-installation checklist
          entries:
            - title: Host preparation checklist
              entries:
                - title: KVM host checklist 
                  url: /kvm-host-configuration-and-preparation-checklist.html
                - title: ESXi host checklist
                  url: /esxi-host-configuration-and-preparation-checklist.html
            - title: Deploy utility required information
              url: /reference_chk_deploy_req_info.html
            - title: ONTAP Select required information
              url: /reference_chk_select_req_info.html
            - title: NVMe host configuration
              url: /task_chk_nvme_configure.html
        - title: Install ONTAP Select Deploy
          url: /task_install_deploy.html
        - title: Deploy a cluster
          url: /task_deploy_cluster.html
        - title: Initial cluster state
          url: /reference_initial_state.html
    - title: Administer
      entries:
        - title: Before you begin
          url: /concept_adm_before.html
        - title: Upgrade nodes
          url: /concept_adm_upgrading_nodes.html
        - title: Diagnostics and support
          url: /task_adm_support.html
        - title: Secure ONTAP Select
          url: /task_adm_security.html
        - title: Confirm network connectivity
          url: /task_adm_connectivity.html
        - title: Administer mediator services
          url: /task_adm_mediators.html
        - title: Clusters
          entries:
            - title: ONTAP Select clusters
              url: /task_adm_clusters.html
            - title: Expand or contract a cluster
              url: /task_cluster_expansion_contraction.html
        - title: Nodes and hosts
          entries:
            - title: Access the VM video console
              url: /task_adm_video_console.html
            - title: Resize the cluster nodes
              url: /task_adm_resize.html
            - title: Replace failed software RAID drives
              url: /task_adm_replace_drives_swraid.html
            - title: Upgrade to VMFS6
              url: /task_adm_upgrade_vmfs6.html
        - title: Licenses
          url: /task_adm_licenses.html
    - title: Deep dive
      entries:
        - title: Storage
          entries:
            - title: General concepts and characteristics
              url: /concept_stor_concepts_chars.html
            - title: Hardware RAID services for local attached storage
              url: /concept_stor_hwraid_local.html
            - title: Software RAID services for local attached storage
              url: /concept_stor_swraid_local.html
            - title: VSAN and external array configurations
              url: /concept_stor_vsan_external.html
            - title: Increase storage capacity
              url: /concept_stor_capacity_inc.html
            - title: Storage efficiency support
              url: /concept_stor_eff_support.html
        - title: Networking
          entries:
            - title: General concepts and characteristics
              url: /concept_nw_concepts_chars.html
            - title: Single and multi node configuration
              url: /concept_nw_single_multi_node.html
            - title: Internal and external networks
              url: /concept_nw_internal_external.html
            - title: Supported configurations
              url: /concept_nw_supported_configs.html
            - title: VMware vSphere VSwitch configuration
              url: /concept_nw_vsphere_vswitch_config.html
            - title: Physical switch configuration
              url: /concept_nw_physical_switch_config.html
            - title: Data and management separation
              url: /concept_nw_data_mgmt_separation.html
        - title: High availability architecture
          entries:
            - title: HA configuration
              url: /concept_ha_config.html
            - title: Synchronous replication and mirrored aggregates
              url: /concept_ha_mirroring.html
            - title: Other high availability functions
              url: /concept_ha_other.html
        - title: Performance
          entries: 
            - title: Performance overview 
              url: /concept_perf_general.html
            - title: ONTAP Select 9.6 performance
              url: /concept_perf_premium_ha_direct_ssd_96.html
    - title: Automate with REST
      entries:
        - title: Concepts
          entries:
            - title: REST web services
              url: /concept_api_rest.html
            - title: Access the Deploy API
              url: /concept_api_how_access.html
          # - title: Deploy API versioning
          #   url: /concept_api_versions.html
            - title: Basic operation
              url: /concept_api_operation.html
            - title: Request and response transaction
              url: /concept_api_transaction.html
            - title: Asynchronous processing
              url: /concept_api_async_proc.html
        - title: Access with a browser
          entries:
            - title: Before you begin
              url: /concept_api_before_browser.html
            - title: Access the doc page
              url: /task_api_access_doc_page.html
            - title: Understand an API call
              url: /task_api_understanding_call.html
        - title: Workflow processes
          entries:
            - title: Before you begin
              url: /concept_api_before_workflows.html
            - title: Workflow 1 Create a cluster
              url: /reference_api_workflow01.html
        - title: Access with Python
          entries:
            - title: Before you begin
              url: /concept_api_before_python.html
            - title: Understand the scripts
              url: /concept_api_understanding_scripts.html
        - title: Python code samples
          entries:
            - title: Create a cluster
              url: /reference_api_script_cc.html
            - title: JSON to create a cluster
              url: /reference_api_json_cc.html
            - title: Add a node license
              url: /reference_api_script_anl.html
            - title: Delete a cluster
              url: /reference_api_script_dc.html
            - title: Common support module
              url: /reference_api_script_common.html
            - title: Resize cluster nodes
              url: /reference_api_script_resize.html
   # - title: Automate with Ansible
   #   url: /concept_automate_ansible.html
    - title: Use the CLI
      entries:
        - title: Sign in using SSH
          url: /task_cli_signing_in.html
        - title: Deploy a cluster
          url: /task_cli_deploy_cluster.html
        - title: Security
          url: /task_cli_security.html
        - title: Network connectivity
          url: /task_cli_connectivity.html
        - title: Clusters
          url: /task_cli_clusters.html
        - title: Nodes and hosts
          entries:
            - title: Upgrade ESXi
              url: /cli-upgrade-esxi.html
            - title: Modify a host management server
              url: /reference_host_modify_command.html
        - title: Deploy utility
          entries:
            - title: Upgrade a Deploy instance
              url: /task_cli_upgrade_deploy.html
            - title: Migrate a Deploy instance
              url: /task_cli_migrate_deploy.html
            - title: Add ONTAP Select images
              url: /task_cli_deploy_image_add.html
            - title: Remove ONTAP Select images
              url: /task_cli_deploy_image_remove.html
            - title: Recover Deploy for a two-node cluster
              url: /task_cli_deploy_recover_two_node.html
    - title: Try ONTAP Select
      entries:
       - title: Access evaluation software
         url: /access-evaluation-software.html
       - title: Deploy a 90-day evaluation instance of a cluster
         url: /deploy-evaluation-ontap-select-ovf-template.html
    - title: FAQ
      url: /reference_faq.html
    - title: Legal notices
      url: /legal-notices.html   
# 2023 Feb 06, Burt 1512785 
