---
sidebar: sidebar
permalink: reference_lic_ontap_features.html
keywords: license, licensing, ontap features, default ontap features
summary: ONTAP Select offers full support for most ONTAP functionality. Many of the ONTAP features are licensed automatically for each node when you deploy a cluster. However some features require a separate license.
---

= ONTAP features
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
ONTAP Select offers full support for most ONTAP functionality. Many of the ONTAP features are licensed automatically for each node when you deploy a cluster. However some features require a separate license.

[NOTE]
ONTAP features that have hardware-specific dependencies are generally not supported with ONTAP Select.

== ONTAP features automatically enabled by default

The following features are included with ONTAP Select and licensed by default:

* CIFS
* Deduplication and compression
* FlexCache
* FlexClone
* iSCSI
* NDMP
* NetApp Volume Encryption (non-restricted countries only)
* NFS
* NVMe over TCP
* ONTAP multitenancy capability
* SnapMirror
* SnapRestore
* SnapVault
* Storage VM disaster recovery (SVM DR)
+
NOTE: ONTAP Select 9.12.1 and later now supports SVM DR as both a source and destination with a maximum of 16 relationships. SVM DR support is limited to the use of the source ONTAP version to versions +2. For example, the ONTAP Select 9.12.1 source can connect to destination ONTAP versions 9.12.1, 9.13.1, or 9.14.1.

== ONTAP features that are separately licensed

You must acquire a separate license for any ONTAP feature that is not enabled by default, including:

* Data Availability Service
* FabricPool
* MetroCluster SDS (ONTAP Select premium license offering)
* ONTAP S3 (zero cost)
* SnapLock Enterprise (SnapLock Compliance is not supported for ONTAP Select)
** Tamperproof Snapshot copies
* SyncMirror (zero cost)

[NOTE]
You do not need a FabricPool license when utilizing StorageGRID Webscale.

.Related information

* link:concept_ots_overview.html#comparing-ontap-select-and-ontap-9[Comparing ONTAP Select and ONTAP 9]
* link:https://mysupport.netapp.com/site/systems/master-license-keys[NetApp ONTAP Master License Keys^]

// 2024 JUN 17, ONTAPDOC-2049
// 2023 Feb 15, GH issue 192
// 2023-APR-05, ONTAPDOC-920
// 2023-OCT-17, Added info about snaplock compliance
// 2023-DEC-07, ONTAPDOC-1523
// 2024-JAN-12, ONTAPDOC-1573
// 2024-MAR-14, ONTAPDOC-1778
// 2024-MAY-28, ONTAPDOC-1981