---
sidebar: sidebar
permalink: reference_plan_dep_general.html
keywords: plan, planning, ontap select deploy, general requirements
summary: There are several general requirements that you should consider as part of planning to install the ONTAP Select Deploy administration utility.
---

= ONTAP Select Deploy general requirements and planning
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several general requirements that you should consider as part of planning to install the ONTAP Select Deploy administration utility.

== Pairing the Deploy utility with the ONTAP Select clusters

You have several options when pairing an instance of the Deploy utility with the ONTAP Select clusters.

[NOTE]
In all deployment scenarios, a single ONTAP Select cluster and the nodes in the cluster can be managed by only one instance of the Deploy administration utility. A cluster cannot be managed by two or more different instances of the Deploy utility.

.One instance of the utility for each ONTAP Select cluster

You can deploy and manage each ONTAP Select cluster using a dedicated instance of the Deploy utility. With this one-to-one configuration, there is a clear separation between each of the utility-to-cluster pairings. This configuration provides a high level of isolation with smaller failure domains.

.One instance of the utility for multiple ONTAP Select clusters

You can deploy and manage multiple ONTAP Select clusters in your organization using a single instance of the Deploy utility. With this one-to-many configuration, all processing and configuration data is managed by the same instance of the Deploy utility.

[NOTE]
One instance of the Deploy utility can administer up to 400 ONTAP Select nodes or 100 clusters.

== Requirements related to the KVM environment

Before installing the Deploy administration utility in a KVM hypervisor environment, you should review the basic requirements and prepare for the deployment.

.Requirements and restrictions for a deployment
There are several requirements and restrictions that you should consider when installing the ONTAP Select Deploy utility in a KVM environment.

.Linux KVM host server hardware requirements
There are several minimum resource requirements that your Linux KVM hypervisor host must meet. Verify that the hosts where ONTAP Select is deployed meet the following basic requirements:

* Linux server:
** The hardware and software must be 64-bit
** The server must adhere to the same supported versions as defined for an ONTAP Select node
* Virtual CPUs (2)
* Virtual memory (4GB)
* Storage (40GB)
* "Dynamic Host Configuration Protocol (DHCP) is enabled (you can also assign a static IP address)

.Network connectivity
Verify that the Deploy virtual machine network interface is configured and can to connect to the ONTAP Select hosts that it manages.

.Support for IP version 4
ONTAP Select Deploy only supports IP version 4 (IPv4). IP version 6 (IPv6) is not supported. This restriction affects ONTAP Select in the following ways:

* You must assign an IPv4 address to the management LIF of the Deploy VM.
* Deploy cannot create ONTAP Select nodes configured to use IPv6 on the ONTAP LIFs.

== Required configuration information

As part of your deployment planning, you should determine the required configuration information before installing the ONTAP Select Deploy administration utility.

.Name of the Deploy VM
The name to use for the VM.

.Name of the Linux KVM host
The Linux KVM host where the Deploy utility is installed.

.Name of the storage pool
The storage pool holding the VM files (approximately 40GB is required).

.Network for the VM
The network where the Deploy VM is connected.

== Optional network configuration information

The Deploy VM is configured using the DHCP by default. However, if needed, you can manually configure the network interface for the VM.

.Host name
The name of the host.

.Host IP address
The static IPv4 address.

.Subnet mask
The subnetwork mask, which is based on the network that the VM is a part of.

.Gateway
The default gateway or router.

.Primary DNS server
The primary domain name server.

.Secondary DNS server
The secondary domain name server.

.Search domains
The search domains to use.

== Authentication using the credential store

The ONTAP Select Deploy credential store is a data base holding account information. Deploy uses the account credentials to perform host authentication as part of cluster creation and management. You should be aware of how the credential store is used as part of planning an ONTAP Select deployment.

[NOTE]
The account information is stored securely in the database using the AES encryption algorithm and SHA-256 hashing algorithm.

.Types of credentials

The following types of credentials are supported:

* Host
Used to authenticate a hypervisor host as part of deploying an ONTAP Select node directly to VMware ESXi
* vCenter
Used to authenticate a vCenter server as part of deploying an ONTAP Select node to ESXi when the host is managed by VMware vCenter

.Access

The credential store is accessed internally as part of performing normal administrative tasks using Deploy, such as adding a hypervisor host. You can also manage the credential store directly through the Deploy web user interface and CLI.

// 2023-09-26, ONTAPDOC-1204