---
sidebar: sidebar
permalink: reference_lic_ontap_features.html
keywords: license, licensing, ontap features, default ontap features
summary: ONTAP Select offers full support for most ONTAP functionality. Many of the ONTAP features are licensed automatically for each node when you deploy a cluster. However some features require a separate license.
---

= ONTAP features
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
ONTAP Select offers full support for most ONTAP functionality. Many of the ONTAP features are licensed automatically for each node when you deploy a cluster. However some features require a separate license.

[NOTE]
ONTAP features that have hardware-specific dependencies are generally not supported with ONTAP Select.

== ONTAP features automatically enabled by default

The following features are included with ONTAP Select and licensed by default:

* NVMe over TCP
* NFS
* CIFS
* iSCSI
* SnapMirror
* SnapVault
* FlexClone
* SnapRestore
* Deduplication and compression
* ONTAP multitenancy capability
* ONTAP S3
* NetApp Volume Encryption (non-restricted countries only)

== ONTAP features that are separately licensed

You must acquire a separate license for any ONTAP feature that is not enabled by default, including:

* SnapLock Enterprise (SnapLock Compliance is not supported for ONTAP Select)
* FabricPool
* Data Availability Service
* FlexCache (zero cost)
* SyncMirror (zero cost)
* MetroCluster SDS (ONTAP Select premium license offering)

[NOTE]
You do not need a FabricPool license when utilizing StorageGRID Webscale.

.Related information

* link:concept_ots_overview.html#comparing-ontap-select-and-ontap-9[Comparing ONTAP Select and ONTAP 9]

// 2023 Feb 15, GH issue 192
// 2023-04-05, ONTAPDOC-920
// 2023-10-17, Added info about snaplock compliance