---
sidebar: sidebar
permalink: reference_additional_info.html
keywords: community, forums, help, support, blogs, videos, imt, release notes, bugs, limitations, known issues
summary: There are additional resources you can access to get help and find more information about ONTAP Select.
---

= Where to get help and find more information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

// DP: October 31 - initial review

[.lead]
There are additional resources you can access to get help and find more information about ONTAP Select.

== ONTAP Select product resources

The following product pages include links to a wide variety of ONTAP Select resources.

* https://www.netapp.com/data-management/software-defined-storage-ontap-select/documentation[NetApp ONTAP Select resources^]

* https://www.netapp.com/us/products/data-management-software/ontap-select-sds.aspx[NetApp ONTAP Select product page^]

== ONTAP 9 resources

* https://docs.netapp.com/us-en/ontap/[ONTAP 9 Documentation^]
+
Provides the documentation for ONTAP 9 (except the CLI commands).

* https://docs.netapp.com/ontap-9/index.jsp[ONTAP 9 Documentation Center^]
+
Provides documentation for the ONTAP 9 CLI commands.

////
=== Videos

There are several helpful videos available at the dedicated YouTube channel.

* https://www.youtube.com/playlist?list=PLdXI3bZJEw7nn1ZJMF3mG2fCBD0Esl--o[NetApp ONTAP Select channel at YouTube^]
////

== Blogs

There is a collection of blog articles covering different aspects of ONTAP Select.

* https://blog.netapp.com/tag/ontap-select/[NetApp ONTAP Select blogs^]

== Community

You can connect with other users to ask questions and contribute to the NetApp ONTAP Select community.

* http://community.netapp.com/t5/forums/filteredbylabelpage/board-id/data-ontap-discussions/label-name/ontap%20select[NetApp Community: ONTAP Select^]

== NetApp Interoperability Matrix Tool

The Interoperability Matrix Tool contains detailed configuration and product support information.

* https://mysupport.netapp.com/matrix/[NetApp IMT^]
