---
sidebar: sidebar
permalink: reference_plan_ots_vnas.html
keywords: plan, planning, vnas, vmware esxi,
summary: There are several planning issues related to the use of VMware ESXi that you should consider.
---

= VMware ESXi requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
ONTAP Select vNAS is a solution allowing the ONTAP Select data stores to be external to the ESXi hypervisor host where the ONTAP Select virtual machine runs. These remote data stores can be accessed through VMware vSAN or a generic external storage array.

== Basic requirements and restrictions

The ONTAP Select vNAS solution can be used with an ONTAP Select cluster of any size.

All related storage components, including hardware, software, and feature requirements, must adhere to the requirements described in the
link:https://mysupport.netapp.com/matrix/[NetApp Interoperability Matrix Tool^]. In addition, ONTAP Select supports all external storage arrays described in the VMware Storage/SAN Compatibility documentation, including iSCSI, NAS (NFSv3), Fibre Channel, and Fibre Channel over Ethernet. External array support is limited by the ESXi version supported by ONTAP Select.

The following VMware features are supported when deploying a cluster with ONTAP Select vNAS:

* VMotion
* High Availability (HA)
* Distributed Resource Scheduler (DRS)

[NOTE]
These VMware features are supported with single-node and multi-node ONTAP Select clusters. When deploying a multi-node cluster, you should make sure that two or more nodes from the same cluster do not run on the same hypervisor host.

The following VMware features are not supported:

* Fault Tolerance (FT)
* Virtual datastore (VVOL)

== Configuration requirements

If you plan to use a VMFS datastore on an external storage array (iSCSI, Fibre Channel, Fibre Channel over Ethernet), you must create a VMFS storage pool before configuring ONTAP Select to use the storage. If you use an NFS datastore, there is no need to create a separate VMFS datastore. All vSAN datastores must be defined within the same ESXi cluster.

[CAUTION]
You must provide a capacity limit for every datastore on VMware vSAN or an external storage array when configuring a host or performing a storage add operation. The capacity you specify must be within the allowed storage limits of the external storage. An error will occur if you do not provide a capacity limit or the external storage runs out of space during the disk creation operation.

== Best practices

Consult the available VMware documentation and adhere to the applicable best practices identified for ESXi hosts. In addition:

* Define dedicated network ports, bandwidth, and vSwitch configurations for the ONTAP Select networks and external storage (VMware vSAN and generic storage array traffic when using iSCSI or NFS)
* Configure the capacity option to restrict storage utilization (ONTAP Select cannot consume the entire capacity of an external vNAS datastore)
* Assure that all generic external storage arrays use the available redundancy and HA features where possible

// 2023-09-25, ONTAPDOC-1204