---
sidebar: sidebar
permalink: reference_new_ots.html
keywords: new features
summary: There are several new and changed features provided with the current release of ONTAP Select.
---

= What's new in ONTAP Select 9.10.1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several new and changed features provided with the current release of ONTAP Select.

== Support for VMware NSX-T

ONTAP Select 9.10.1 has been qualified for VMware NSX-T version 3.1.2. There are no functional issues or deficiencies when using NSX-T with an ONTAP Select single-node Cluster deployed with an OVA file and the ONTAP Select Deploy administration utility. However, when using NSX-T with an ONTAP Select multi-node cluster, you should note the following requirements and limitations:

Cluster MTU::
You must manually adjust the cluster MTU size to 8800 before deploying the cluster to account for the additional overhead. The VMware guidance is to allow for a 200-byte buffer when using NSX-T.

Network 4x10Gb configuration::
For ONTAP Select deployments on a VMware ESXi host configured with four NICs, the Deploy utility will prompt you to follow the best practice of splitting internal traffic across two different port groups and external traffic across two different port groups. However, when using an overlay network this configuration does not work and you should disregard the recommendation. In this case, you should instead use only one internal port group and one external port group.

Network connectivity checker::
The network connectivity checker available through the Deploy CLI fails when it is run against an NSX-T based network.

== KVM hypervisor is no longer supported

Beginning with ONTAP Select 9.10.1 you can no longer deploy a new cluster on the KVM hypervisor. However, if you upgrade a cluster from a previous release to 9.10.1 you can still use the Deploy utility to administer the cluster.
