---
sidebar: sidebar
permalink: reference_plan_ots_storage.html
keywords: plan, planning, storage, software raid, hardware raid, raid, nvme
summary: There are several planning issues related to ONTAP Select host storage that you should consider.
---
= ONTAP Select storage and RAID considerations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several planning issues related to ONTAP Select host storage that you should consider.

NOTE: External storage support information is outlined for ESXi and KVM hosts. For more information, refer to link:reference_plan_ots_vnas.html[VMware ESXi requirements] and link:reference_plan_ots_kvm.html[KVM requirements].

== Hardware RAID controller requirements

The RAID controller on the hypervisor host where you deploy ONTAP Select must meet several requirements.

[NOTE]
A host where ONTAP Select runs requires local physical drives when using a hardware RAID controller or the software RAID capability provided with ONTAP Select. If you use the ONTAP Select vNAS solution to access external storage, a local RAID controller and software RAID capability are not used.

The minimum requirements for the RAID controller include:

* 12 Gbps throughput
* 512 MB internal battery-backed or flash (SuperCAP) cache
* Configured in write back mode:
** Enable failback mode to “write through” (if supported)
** Enable “always read ahead” policy (if supported)
* All local disks behind the RAID controller should be configured as a single RAID group; use multiple RAID controllers if needed:
** Disable the local drive cache for RAID group, which is fundamental to preserving data integrity.
* Performing LUN configuration based on the following guidelines:
** If the RAID group size exceeds the maximum LUN size of 64TB, configure multiple equal-sized LUNs consuming all the available storage within the RAID group.
** If the RAID group size is smaller than the maximum LUN size of 64TB, configure one LUN consuming all available storage within the RAID group.

== Software RAID requirements

When deploying an ONTAP Select cluster on the hypervisor, you can use the software RAID capability provided by ONTAP Select instead of a local hardware RAID controller. Review the following requirements and restrictions before deploying a cluster using software RAID.

=== General requirements

The environment for a software RAID deployment must meet the following core requirements:

* VMware ESXi 8.0 GA (build 20513097) or later
* ONTAP Select premium license or higher
* Local SSD drives only
* Separation of system disks from the root and data aggregates
* No hardware RAID controller on the host

[NOTE]
If a hardware RAID controller is present, see the link:concept_stor_concepts_chars.html[Deep dive storage] section for additional configuration requirements.

=== ESXi specific requirements

* VMware ESXi 8.0 GA (build 20513097) or later
* VMware VMotion, HA, and DRS are not supported
* You cannot use software RAID with a node that has been upgraded from ONTAP Select 9.4 or earlier. If this is the case, you need to create a new node for software RAID deployment. 

=== KVM specific requirements

There are also specific software package configuration requirements. See the link:https://docs.netapp.com/us-en/ontap-select/kvm-host-configuration-and-preparation-checklist.html#prepare-linux-server[preparation of the Linux server] step for more information.

Media expectations for KVM::
The SSD flash storage devices used must meet the following additional requirements:

* The SSD devices must accurately and persistently report themselves to the Linux host through the following methods:
** # cat /sys/block/<device>/queue/rotational
+
The value reported for these commands must be '0'.

* It is expected that the devices are connected to an HBA or, in some cases, to a RAID controller configured to operate in JBOD mode. When using a RAID controller, the device function must be passed through the host without overlaying any RAID functionality. When using a RAID controller in JBOD mode, you should review the RAID documentation or contact the vendor as needed to make sure the device reports the rotational speed as '0'.
* There are two separate storage components:
** Virtual machine storage
+
This is an LVM pool (storage pool) containing the system data used to host the ONTAP Select virtual machine. The LVM pool must be backed by a high endurance flash device, and can be either SAS, SATA, or NVMe. An NVMe device is recommended for improved performance.

** Data disks
+
This is a set of SAS or SATA SSD drives used for data management. The SSD devices should be enterprise grade and durable. The NVMe interface is not supported.

* All devices must be formatted with 512BPS.


=== ONTAP Select node configuration

You must configure each ONTAP Select node and hypervisor host as follows to separate the system disks from the root and data aggregates:

* Create a system storage pool
You must create a storage pool for the ONTAP Select system data. You must attach the storage pool as part of configuring the ONTAP Select node.
* Attach necessary physical disks
The hypervisor host must have the required SSD disks attached and available for use by the ONTAP Select virtual machine. These drives hold the root and data aggregates. You must attach the storage disks as part of configuring the ONTAP Select node.

== Storage capacity restrictions

// Also see 1210248

As part of planning an ONTAP Select deployment, you should be aware of the restrictions related to storage allocation and use.

The most important storage restrictions are presented below. You should also review the link:https://mysupport.netapp.com/matrix/[Interoperability Matrix Tool^] for more detailed information.

[TIP]
ONTAP Select enforces several restrictions related to storage allocation and use. Before you deploy an ONTAP Select cluster or purchase a license, you should be familiar with these restrictions. See the link:https://docs.netapp.com/us-en/ontap-select/concept_lic_evaluation.html[License] section for more information.

=== Calculate raw storage capacity

The ONTAP Select storage capacity corresponds to the total allowable size of the virtual data and root disks attached to the ONTAP Select virtual machine. You should consider this when allocating capacity.

=== Minimum storage capacity for a single-node cluster

The minimum size of the storage pool allocated for the node in a single-node cluster is:

* Evaluation: 500 GB
* Production: 1.0 TB

The minimum allocation for a production deployment consists of 1 TB for user data, plus approximately 266 GB used by various ONTAP Select internal processes, which is considered required overhead.

=== Minimum storage capacity for a multi-node cluster

The minimum size of the storage pool allocated for each node in a multi-node cluster is:

* Evaluation: 1.9 TB
* Production: 2.0 TB

The minimum allocation for a production deployment consists of 2 TB for user data, plus approximately 266 GB used by various ONTAP Select internal processes, which is considered required overhead.

[NOTE]
====
Each node in an HA pair must have the same storage capacity.

When estimating the amount of storage for an HA pair, you must consider that all aggregates (root and data) are mirrored. As a result, each plex of the aggregate consumes an equal amount of storage.

For example, when a 2TB aggregate is created, it allocates 2TB to two plex instances (2TB for plex0 and 2TB for plex1) or 4TB of the total licensed amount of storage.
====

=== Storage capacity and multiple storage pools

You can configure each ONTAP Select node to use up to 400 TB of storage when using local direct-attached storage, VMware vSAN, or external storage arrays. However, a single storage pool has a maximum size of 64 TB when using direct-attached storage or external storage arrays. Therefore, if you plan to use more than 64 TB of storage in these situations, you must allocate multiple storage pools as follows:

* Assign the initial storage pool during the cluster creation process
* Increase the node storage by allocating one or more additional storage pools

[NOTE]
A 2% buffer is left unused in each storage pool and does not require a capacity license. ONTAP Select does not use this storage unless you specify a capacity cap. If  you specify a capacity cap, then ONTAP Select uses that amount of storage unless the amount specified falls in the 2% buffer zone. The buffer is needed to prevent occasional errors that occur when attempting to allocate all of the space in a storage pool.

=== Storage capacity and VMware vSAN

When using VMware vSAN, a datastore can be larger than 64 TB. However, you can only initially allocate up to 64 TB when creating the ONTAP Select cluster. After the cluster is created, you can allocate additional storage from the existing vSAN datastore. The vSAN datastore capacity that can be consumed by ONTAP Select is based on the VM storage policy set.

=== Best practices

You should consider the following recommendations regarding the hypervisor core hardware:

* All drives in a single ONTAP Select aggregate should be the same type. For example, you should not mix HDD and SSD drives in the same aggregate.

== Additional disk drive requirements based on the platform license

The drives you choose are limited based on the platform license offering.

[NOTE]
The disk drive requirements apply when using a local RAID controller and drives, as well as software RAID. These requirements do not apply to external storage accessed through the ONTAP Select vNAS solution.

.Standard

* 8 to 60 internal HDD (NL-SAS, SATA, 10K SAS)

.Premium

* 8 to 60 internal HDD (NL-SAS, SATA, 10K SAS)
* 4 to 60 internal SSD

.Premium XL

* 8 to 60 internal HDD (NL-SAS, SATA, 10K SAS)
* 4 to 60 internal SSD
* 4 to 14 internal NVMe

[NOTE]
Software RAID with local DAS drives is supported with the premium license (SSD only) and premium XL license (SSD or NVMe).

== NVMe drives with software RAID

You can configure software RAID to use NVMe SSD drives. Your environment must meet the following requirements:

* ONTAP Select with a supported Deploy administration utility
* Premium XL platform license offering or a 90-day evaluation license
* VMware ESXi version 8.0 or later
* NVMe devices conforming to specification 1.0 or later

You need to manually configure the NVMe drives before using them. See link:task_chk_nvme_configure.html[Configure a host to use NVMe drives] for more information.

// 2026 JAN 15, ontap-select-issue-310 and NADIAA updates
// 2023-09-12, ONTAPDOC-1174
// 2023-09-25, ONTAPDOC-1204
// 2023-10-17, Removed mention of old OTS versions
// 2023-11-28, ONTAPDOC-1254