---
sidebar: sidebar
permalink: reference_plan_dep_general.html
keywords: plan, planning, ontap select deploy, general requirements
summary: There are several general requirements that you should consider as part of planning to install the ONTAP Select Deploy administration utility.
---

= ONTAP Select Deploy general requirements and planning
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several general requirements that you should consider as part of planning to install the ONTAP Select Deploy administration utility.

== Pairing the Deploy utility with the ONTAP Select clusters

You have several options when pairing an instance of the Deploy utility with the ONTAP Select clusters.

[NOTE]
In all deployment scenarios, a single ONTAP Select cluster and the nodes in the cluster can be managed by only one instance of the Deploy administration utility. A cluster cannot be managed by two or more different instances of the Deploy utility.

.One instance of the utility for each ONTAP Select cluster

You can deploy and manage each ONTAP Select cluster using a dedicated instance of the Deploy utility. With this one-to-one configuration, there is a clear separation between each of the utility-to-cluster pairings. This configuration provides a high level of isolation with smaller failure domains.

.One instance of the utility for multiple ONTAP Select clusters

You can deploy and manage multiple ONTAP Select clusters in your organization using a single instance of the Deploy utility. With this one-to-many configuration, all processing and configuration data is managed by the same instance of the Deploy utility.

[NOTE]
One instance of the Deploy utility can administer up to 400 ONTAP Select nodes or 100 clusters.

== Authentication using the credential store

The ONTAP Select Deploy credential store is a database holding account information. Deploy uses the account credentials to perform host authentication as part of cluster creation and management. You should be aware of how the credential store is used as part of planning an ONTAP Select deployment.

[NOTE]
The account information is stored securely in the database using the AES encryption algorithm and SHA-256 hashing algorithm.

.Types of credentials

The following types of credentials are supported:

* Host
Used to authenticate a hypervisor host as part of deploying an ONTAP Select node directly to VMware ESXi
* vCenter
Used to authenticate a vCenter server as part of deploying an ONTAP Select node to ESXi when the host is managed by VMware vCenter

.Access

The credential store is accessed internally as part of performing normal administrative tasks using Deploy, such as adding a hypervisor host. You can also manage the credential store directly through the Deploy web user interface and CLI.
