---
sidebar: sidebar
permalink: reference_new_ots.html
keywords: new features
// summary: The current release includes several new features and improvements specific to ONTAP Select.
summary: The current release does not include any new features or improvements specific to ONTAP Select.
---

= What's new in this release
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
// The current release includes several new features and improvements specific to ONTAP Select.
The current release does not include any new features or improvements specific to ONTAP Select. 

== ONTAP Release Notes

ONTAP Select benefits from most of the new developments in the current release of the core ONTAP product. Refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP Release Notes^] for information about new features or improvements in each ONTAP 9 release.

== ONTAP 9.11.1

ONTAP Select 9.11.1 includes several new features and improvements. 

=== Enhanced VMware ESXi support

ONTAP Select 9.11.1 includes support for VMware ESXi 7.0 U3C.

=== Support for VMware NSX-T

ONTAP Select 9.10.1 and later releases have been qualified for VMware NSX-T version 3.1.2. There are no functional issues or deficiencies when using NSX-T with an ONTAP Select single-node Cluster deployed with an OVA file and the ONTAP Select Deploy administration utility. However, when using NSX-T with an ONTAP Select multi-node cluster, you should note the following requirements and limitations for ONTAP Select 9.11.1:

==== Network connectivity checker
The network connectivity checker available through the Deploy CLI fails when it is run against an NSX-T based network.

=== KVM hypervisor is no longer supported

Beginning with ONTAP Select 9.10.1 and later releases, you were no longer able to create new KVM-based clusters or add KVM-based hosts using the Deploy utility. Further, 9.10.1 was the last release supporting the manageability functions, such as bring online, with existing KVM clusters and hosts.
Then beginning with ONTAP Select 9.11.1 and later releases, all manageability functionality is no longer available for existing KVM clusters and hosts, except the take offline and delete functions.
NetApp has strongly recommended that customers plan and execute a full data migration from ONTAP Select for KVM to any other ONTAP platform, including ONTAP Select for ESXi. For more information, see the https://mysupport.netapp.com/info/communications/ECMLP2877451.html[EOA Notice^]

== ONTAP 9.10.1

ONTAP Select 9.10.1 includes several new features and improvements.

=== Support for VMware NSX-T

ONTAP Select 9.10.1 has been qualified for VMware NSX-T version 3.1.2. There are no functional issues or deficiencies when using NSX-T with an ONTAP Select single-node Cluster deployed with an OVA file and the ONTAP Select Deploy administration utility. However, when using NSX-T with an ONTAP Select multi-node cluster, you should note the following requirements and limitations:

==== Cluster MTU
You must manually adjust the cluster MTU size to 8800 before deploying the cluster to account for the additional overhead. The VMware guidance is to allow for a 200-byte buffer when using NSX-T.

==== Network 4x10Gb configuration
For ONTAP Select deployments on a VMware ESXi host configured with four NICs, the Deploy utility will prompt you to follow the best practice of splitting internal traffic across two different port groups and external traffic across two different port groups. However, when using an overlay network this configuration does not work and you should disregard the recommendation. In this case, you should instead use only one internal port group and one external port group.

==== Network connectivity checker
The network connectivity checker available through the Deploy CLI fails when it is run against an NSX-T based network.

=== KVM hypervisor is no longer supported

Beginning with ONTAP Select 9.10.1 you can no longer deploy a new cluster on the KVM hypervisor. However, if you upgrade a cluster from a previous release to 9.10.1 you can still use the Deploy utility to administer the cluster.