---
sidebar: sidebar
permalink: reference_plan_ots_networking.html
keywords: plan, planning, networking, network, drivers, vmxnet3, cluster mtu, firewall
summary: You must configure the hypervisor network correctly before deploying ONTAP Select.
---

= Networking considerations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You must configure the hypervisor network correctly before deploying ONTAP Select.

== Virtual switch options

You must configure a virtual switch on each of the ONTAP Select hosts to support the external network and internal network (multi-node clusters only). As part of deploying a multi-node cluster, you should test the network connectivity on the internal cluster network.

[NOTE]
To learn more about how to configure a vSwitch on a hypervisor host and the high speed interface feature, see the link:concept_nw_concepts_chars.html[Deep dive networking] section.

== Upgrade to VMXNET3 (ESXi only)

Beginning with ONTAP Select 9.5 using Deploy 2.10, VMXNET3 is the default network driver included with new cluster deployments on VMware ESXi. If you upgrade an older ONTAP Select node to version 9.5 or later, the driver is not automatically upgraded.

== Cluster MTU

A separate internal network is used to connect the ONTAP Select nodes in a multi-node cluster. Typically the MTU size for this network is 9000. However, there are situations where this MTU size is too large for the network connecting the ONTAP Select nodes. To accommodate the smaller frames, the MTU size used by ONTAP Select on the internal network can be in the range of 7500-9000 bytes.

The MTU size is displayed in the Cluster Details section of the cluster creation page. The value is determined by the Deploy administration utility as follows:

. Initial default of 9000.
. As you add the hosts and networks for the HA pairs, the MTU value is reduced as needed, based on the configuration of the vSwitches in the network.
. The final cluster MTU value for the cluster is set after you have added all the HA pairs and are ready to create the cluster.

[NOTE]
You can manually set the cluster MTU value if needed, based on the design of your network.

== Two-NIC host with standard vSwitch (ESXi only)

In order to improve ONTAP Select performance in a two-NIC configuration, you should isolate the internal and external network traffic using two port groups. This recommendation applies to the following specific configuration:

* ONTAP Select multi-node cluster
* Two NICs (NIC1 and NIC2)
* Standard vSwitch

In this environment, you should configure the traffic using two port groups as follows:

.Port group 1

* Internal network (cluster, RSM, HA-IC traffic)
* NIC1 is active
* NIC2 in standby

.Port group 2

* External network (data and management traffic)
* NIC1 is standby
* NIC2 in active

See the link:concept_nw_concepts_chars.html[Deep dive networking] section for more information about two-NIC deployments.

== Four-NIC host with standard vSwitch (ESXi only)

In order to improve ONTAP Select performance in a four-NIC configuration, you should isolate the internal and external network traffic using four port groups. This recommendation applies to the following specific configuration:

* ONTAP Select multi-node cluster
* Four NICs (NIC1, NIC2, NIC3, and NIC4)
* Standard vSwitch

In this environment, you should configure the traffic using four port groups as follows:

.Port group 1

* Internal network (cluster, RSM traffic)
* NIC1 is active
* NIC2, NIC3, NIC4 in standby

.Port group 2

* Internal network (cluster, HA-IC traffic)
* NIC3 is active
* NIC1, NIC2, NIC4 in standby

.Port group 3

* External network (data and management traffic)
* NIC2 is active
* NIC1, NIC3, NIC4 in standby

.Port group 4

* External network (data traffic)
* NIC4 is active
* NIC1, NIC2, NIC3 in standby

See the link:concept_nw_concepts_chars.html[Deep dive networking] section for more information about four-NIC deployments.

== Network traffic requirements

You must make sure that your firewalls are configured properly to allow the network traffic to flow among the various participants in an ONTAP Select deployment environment.

.Participants

There are several participants or entities that exchange network traffic as part of an ONTAP Select deployment. These are introduced, and then used in the summary description of the network traffic requirements.

* Deploy
ONTAP Select Deploy administration utility
* vSphere (ESXi only)
Either a vSphere server or ESXi host, depending on how the host is managed in your cluster deployment
* Hypervisor server
ESXi hypervisor host or Linux KVM host
* OTS node
An ONTAP Select node
* OTS cluster
An ONTAP Select cluster
* Admin WS
Local administrative workstation

.Summary of network traffic requirements

The following table describes the network traffic requirements for an ONTAP Select deployment.

[cols="20,20,35,25"*,options="header"]
|===
|Protocol / Port
|ESXi / KVM
|Direction
|Description

|TLS (443)
|ESXi
|Deploy to vCenter server (managed) or ESXi (managed or unmanaged)
|VMware VIX API

|902
|ESXi
|Deploy to vCenter server (managed) or ESXi (unmanaged)
|VMware VIX API

|ICMP
|ESXi or KVM
|Deploy to hypervisor server
|Ping

|ICMP
|ESXi or KVM
|Deploy to each OTS node
|Ping

|SSH (22)
|ESXi or KVM
|Admin WS to each OTS node
|Administration

|SSH (22)
|KVM
|Deploy to hypervisor server nodes
|Access hypervisor server

|TLS (443)
|ESXi or KVM
|Deploy to OTS nodes and clusters
|Access ONTAP

|TLS (443)
|ESXi or KVM
|Each OTS node to Deploy
|Access Deploy (capacity pools licensing)

|iSCSI (3260)
|ESXi or KVM
|Each OTS node to Deploy
|Mediator/Mailbox disk

|===

// 2023-09-25, ONTAPDOC-1204
// 2023-10-17, Removed mention of old OTS versions