---
sidebar: sidebar
permalink: reference_plan_ots_mcc_sds.html
keywords: plan, planning, metrocluster, metrocluster sds
summary: There are several requirements MetroCluster SDS that you should consider as part of planning an ONTAP Select deployment.
---

= Preparing for a MetroCluster SDS deployment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
MetroCluster SDS is a configuration option when creating a two-node ONTAP Select cluster. It is similar to a Remote Office/Branch Office (ROBO) deployment, however the distance between the two nodes can be up to 10 km. This enhanced two-node deployment provides additional use case scenarios. You should be aware of the requirements and restrictions as part of preparing to deploy MetroCluster SDS.

Before deploying MetroCluster SDS, verify that the following requirements are met.

.Licensing

Each node must have a premium or higher ONTAP Select license.

.Hypervisor platforms

MetroCluster SDS can be deployed on the same VMware ESXi and KVM hypervisors as supported for a two-node cluster in a ROBO environment.

[NOTE]
====
Beginning with ONTAP Select 9.14.1, support for KVM hypervisor has been reinstated. Previously, support for deploying a new cluster on a KVM hypervisor was removed in ONTAP Select 9.10.1 and support for managing existing KVM clusters and hosts, except to take offline or delete, was removed in ONTAP Select 9.11.1.
====

.Network configuration

Layer 2 connectivity is required between the participating sites. Both 10GbE and 1GbE are supported, including the following configurations:

* 1 x 10GbE
* 4 x 1GbE

[NOTE]
The data serving ports and interconnect ports must be connected to the same first switch.

.Latency between the nodes

The network between the two nodes must support a mean latency of 5 ms with an additional 5 ms periodic jitter. Before deploying the cluster, you must test the network using the procedure described in the link:concept_nw_concepts_chars.html[Deep dive networking] section.

.Mediator service

As with all two-node ONTAP Select clusters, there is a separate mediator service contained in the Deploy virtual machine that monitors the nodes and assists in managing failures. With the enhanced distance available with MetroCluster SDS, this creates three distinct sites in the network topology. Latency on the link between the mediator and a node should be 125 ms round-trip or less.

.Storage

Direct-attached storage (DAS) is supported using either HDD and SSD disks. vNAS is also supported, including external storage arrays and vSAN in a VMware environment.

[NOTE]
When deploying MetroCluster SDS, you cannot use vSAN in a distributed or "stretched" topology.

.Static IP address assigned to Deploy

You must assign a static IP address to the Deploy administration utility. This requirement applies to all Deploy instances that manage one or more ONTAP Select two-node clusters.

// 2023-09-26, ONTAPDOC-1204