---
sidebar: sidebar
permalink: reference_plan_ots_general.html
keywords: plan, planning, general requirements
summary: There are several general requirements that you should consider as part of planning an ONTAP Select deployment.
---

= General requirements and planning considerations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several general requirements you should consider as part of planning an ONTAP Select deployment.

== Required Linux knowledge and skills for KVM

Linux with the KVM hypervisor is a complex environment to work in. Before deploying ONTAP Select on KVM, you must have the necessary knowledge and skills.

Linux server distribution::
You should have experience with the specific Linux distribution to be used for your ONTAP Select Deployment. Specifically, you should be able to perform the following tasks:

* Install the Linux distribution
* Configure the system using the CLI
* Add software packages as well as any dependencies

For more information on preparing your Linux server, including the required configuration and software packages, see the host configuration checklist. Refer to the hypervisor requirements for the currently supported Linux distributions.

KVM deployment and administration::
You should be familiar with general virtualization concepts. In addition, there are several Linux CLI commands that you must use as part of installing and administering ONTAP Select in a KVM environment:

* `virt-install`
* `virsh`
* `lsblk`
* `lvs`
* `vgs`
* `pvs`

Networking and Open vSwitch configuration::
You should be familiar with networking concepts and the configuration of network switches. In addition, you should have experience with Open vSwitch. You must use the following network commands a part of configuring the ONTAP Select network in a KVM environment:

* `ovs-vsctl`
* `ip`
* `ip link`
* `systemctl`


== Cluster size and related considerations

There are several planning issues related to the cluster size that you should consider.

Number of nodes in the cluster::
An ONTAP Select cluster is composed of one, two, four, six, or eight nodes. You should determine the size of the cluster based on the application requirements. For example, if HA capability is needed for an enterprise deployment, then a multi-node cluster should be used.

Dedicated versus collocated::
Based on the application type, you should determine if the deployment follows the dedicated or collocated model. Note that the collocated model can be more complex due to the workload diversity and tighter integration.

== Hypervisor host considerations

There are several planning issues related to the hypervisor host that you should consider.

[CAUTION]
You should not directly modify the configuration of an ONTAP Select virtual machine unless directed to do so by NetApp support. A virtual machine should only be configured and modified through the Deploy administration utility. Making changes to an ONTAP Select virtual machine outside of the Deploy utility without assistance from NetApp support can cause the virtual machine to fail and render it unusable.

Hypervisor independent::
Both ONTAP Select and the ONTAP Select Deploy administration utility are hypervisor-independent. The following hypervisors are supported for both.

* VMware ESXi
* Kernel-based Virtual Machine (KVM)

[NOTE]
Beginning with ONTAP Select 9.14.1, support for KVM hypervisor has been reinstated. Previously, support for deploying a new cluster on a KVM hypervisor was removed in ONTAP Select 9.10.1 and support for managing existing KVM clusters and hosts, except to take offline or delete, was removed in ONTAP Select 9.11.1.

Refer to the hypervisor-specific planning information and release notes for additional details regarding the supported platforms.

Hypervisor for ONTAP Select nodes and administration utility::
Both the Deploy administration utility and ONTAP Select nodes run as virtual machines. The hypervisor you choose for the Deploy utility is independent of the hypervisor you choose for the ONTAP Select nodes. You have complete flexibility when pairing the two:

* Deploy utility running on VMware ESXi can create and manage ONTAP Select clusters on either VMware ESXi or KVM
* Deploy utility running on KVM can create and manage ONTAP Select clusters on either VMware ESXi or KVM

One or more instances of ONTAP Select node per host::
Each ONTAP Select node runs as a dedicated virtual machine. You can create multiple nodes on the same hypervisor host, with the following restrictions:

* Multiple nodes from a single ONTAP Select cluster cannot run on the same host. All the nodes on a specific host must be from different ONTAP Select clusters.
* You must use external storage.
* If you use software RAID, you can only deploy one ONTAP Select node on the host.

Hypervisor consistency for the nodes within a cluster::
All of the hosts within an ONTAP Select cluster must run on the same version and release of the hypervisor software.

Number of physical ports on each host::
You must configure each host to use one, two, or four physical ports. Although you have flexibility when configuring the network ports, you should follow these recommendations where possible:

* A host in a single-node cluster should have two physical ports.
* Each host in a multi-node cluster should have four physical ports

Integrating ONTAP Select with an ONTAP hardware-based cluster::
You cannot add an ONTAP Select node directly to an ONTAP hardware-based cluster. However, you can optionally establish a cluster peering relationship between an ONTAP Select cluster and a hardware-based ONTAP cluster.

== Storage considerations

There are several planning issues related to host storage that you should consider.

RAID type::
When using direct-attached storage (DAS) on ESXi, you should decide whether to use a local hardware RAID controller or the software RAID feature included with ONTAP Select. If you use software RAID, see link:reference_plan_ots_storage.html[Storage and RAID considerations] for more information.

Local storage::
When using local storage managed by a RAID controller, you must decide the following:

* Whether to use one or more RAID groups
* Whether to use one or more LUNs

External storage::
When using the ONTAP Select vNAS solution, you must decide where the remote datastores are located and how they are accessed. ONTAP Select vNAS supports the following configurations:

* VMware vSAN
* Generic external storage array

Estimate for the storage needed::
You should determine how much storage is required for the ONTAP Select nodes. This information is required as part of acquiring the purchased licenses with storage capacity. Refer to Storage capacity restrictions for more information.

[NOTE]
The ONTAP Select storage capacity corresponds to the total allowable size of the data disks attached to the ONTAP Select virtual machine.

Licensing model for production deployment::
You must select the capacity tiers or capacity pools licensing model for each ONTAP Select cluster deployed in a production environment. Review the section _License_ for more information.

== Authentication using the credential store

The ONTAP Select Deploy credential store is a data base holding account information. Deploy uses the account credentials to perform host authentication as part of cluster creation and management. You should be aware of how the credential store is used as part of planning an ONTAP Select deployment.

NOTE: The account information is stored securely in the data base using the Advanced Encryption Standard (AES) encryption algorithm and SHA-256 hashing algorithm.

Types of credentials::
The following types of credentials are supported:

* host
+
The *host* credential is used to authenticate a hypervisor host as part of deploying an ONTAP Select node directly to ESXi or KVM.

* vcenter
+
The *vcenter* credential is used to authenticate a vCenter server as part of deploying an ONTAP Select node to ESXi when the host is managed by VMware vCenter.

Access::
The credential store is accessed internally as part of performing normal administrative tasks using Deploy, such as adding a hypervisor host. You can also manage the credential store directly through the Deploy web user interface and CLI.

.Related information

* link:reference_plan_ots_storage.html[Storage and RAID considerations]

// 2023-09-25, ONTAPDOC-1204