---
sidebar: sidebar
permalink: reference_chk_select_req_info.html
keywords: ontap select, pre-installation, vmware
summary: As part of preparing to deploy an ONTAP Select cluster in a VMware environment, collect the information required when using the ONTAP Select Deploy administration utility to deploy and configure the cluster.
---

= Required information for ONTAP Select installation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
As part of preparing to deploy an ONTAP Select cluster in a VMware environment, collect the information required when using the ONTAP Select Deploy administration utility to deploy and configure the cluster.

Some of the information you collect applies to the cluster itself, while other information applies to the individual nodes in the cluster.

== Cluster-level information

You must collect information related to the ONTAP Select cluster.

[cols=2*,options="header",cols="35,65"]
|===
| Cluster information
| Description
| Name of the cluster | Unique identifier of the cluster.
| Licensing mode | Evaluation or purchased licensing.
| IP configuration for the cluster | IP configuration for the clusters and nodes, including:
* Management IP address of the cluster
* Subnet mask
* Default gateway
|===

== Host-level information

You must collect information related to each of the nodes in the ONTAP Select cluster.

[cols=2*,options="header",cols="35,65"]
|===
| Cluster information
| Description
| Name of the host |Unique identifier of the host.
| Domain name of the host | Fully qualified domain name of the host.
| IP configuration for the nodes | Management IP address for each node in the cluster.
| Mirror node | Name of the associated node in the HA pair (multi-node clusters only).
| Storage pool | Name of the storage pool that is used.
| Storage disks | List of disks if using software RAID.
| Serial number | If you are deploying with a purchased license, the unique nine-digit serial number provided by NetApp.
|===
