---
sidebar: sidebar
permalink: reference_plan_dep_vmware.html
keywords: plan, planning, ontap select deploy, vmware requirements
summary: There are several requirements and restrictions specific to the VMware environment that you should consider before installing the ONTAP Select Deploy utility in a VMware environment.
---

= VMware hypervisor environment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several requirements and restrictions specific to the VMware environment that you should consider before installing the ONTAP Select Deploy utility in a VMware environment.

== ESXi host server hardware requirements

There are several minimum resource requirements that your ESXi hypervisor host must meet. You should make sure that the hosts where ONTAP Select is deployed meet the following basic requirements:

* ESXi server:
** Hardware and software must be 64-bit
** Must adhere to the same supported versions as defined for an ONTAP Select node
* Virtual CPUs (2)
* Virtual memory (4 GB)
* Storage (40 GB)
* DHCP enabled (can also assign a static IP address)

== Network connectivity

You must make sure that the ONTAP Select Deploy virtual machine network interface is configured and has a single management IP address. You can use DHCP to dynamically assign an IP address or manually configure a static IP address.

Depending on your deployment decisions, the Deploy VM must be able to connect to the vCenter server, ESXi hypervisor hosts, and ONTAP Select nodes it manages. You must configure your firewalls to allow the required traffic.

Deploy uses the VMware VIX API to communicate with the vCenter server and ESXi hosts. Initially, it establishes a connection using SOAP over SSL on TCP port 443. After this, a connection is opened using SSL on port 902. In addition, Deploy issues PING commands to verify there is an ESXi host at the IP address you specify.

Deploy must also be able to communicate with the ONTAP Select node and cluster management IP addresses using the following protocols:

* PING command (ICMP)
* SSH (port 22)
* SSL (port 443)

== Support for IP version 4

ONTAP Select Deploy only supports IP version 4 (IPv4). IP version 6 (IPv6) is not supported. This restriction affects ONTAP Select in the following ways:

* You must assign an IPv4 address to the management LIF of the Deploy virtual machine.
* Deploy cannot create ONTAP Select nodes configured to use IPv6 on the ONTAP LIFs.

== VMware vCenter language restriction

If you use ONTAP Select Deploy to create a cluster running on ESXi with vCenter on a Windows Server, you must use an English language version. ONTAP Select Deploy does not support vCenter on non-English versions of Windows.
