---
sidebar: sidebar
permalink: reference_plan_ots_two_node.html
keywords: plan, planning, two nodes, two node clusters
summary: Deploying a two-node cluster with HA involves the same planning and configuration used with other cluster node configurations. However, there are several differences you should be aware of when creating a two-node cluster.
---

= ONTAP Select two-node clusters with HA
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Deploying a two-node cluster with HA involves the same planning and configuration used with other cluster node configurations. However, there are several differences you should be aware of when creating a two-node cluster.

.Target environment

The two-node cluster consists of one HA pair and has been specifically designed for remote office and branch office deployments.

[NOTE]
While designed primarily for the remote and branch office environment, you can also deploy a two-node cluster in the data center if needed.

.Licensing

You can deploy a two-node cluster using any VMware vSphere license. However, the VMware ROBO Standard and Advanced licenses are ideal for remote and branch office deployments.

.Mediator service

When a cluster consists of two nodes, it is not possible to achieve the quorum required when a node fails or loses communication. To resolve these types of split-brain situations, every instance of the ONTAP Select Deploy utility includes a mediator service. This service connects to each node in the active two-node clusters to monitor the HA pairs and assist in managing failures. The mediator service maintains the HA state information at a dedicated iSCSI target associated with each two-node cluster.

[CAUTION]
If you have one or more active two-node clusters, the ONTAP Select Deploy virtual machine administering the clusters must be running at all times. If the ONTAP Select Deploy virtual machine is halted or fails, the mediator service is unavailable and HA capability is lost for the two-node clusters.

.Location of the cluster and mediator service

Because the two-node clusters are typically deployed in a remote or branch office, they can be remote from the corporate data center and the ONTAP Select Deploy utility providing administrative support. With this configuration, the management traffic between the ONTAP Select Deploy utility and cluster flows over the WAN. See the release notes for more information about limitations and restrictions.

.Back up the ONTAP Select Deploy configuration data

It is a best practice to back up the ONTAP Select Deploy configuration data on a regular basis, including after creating a cluster. This becomes particularly important with two-node clusters, because of the mediator configuration data included with the backup.

.Steps

. Sign in to the ONTAP Select Deploy utility CLI using SSH with the administrator account.

. Create a backup of the ONTAP Select Deploy configuration data, which is stored in an internal directory at the ONTAP Select Deploy server:
+
`deploy backup create`

. Provide a password for the backup when prompted.
+
The backup file is encrypted based on the password.

. Display the available backups in the system:
+
`deploy backup show -detailed`

. Select your backup file based on the date in the *Created* field and record the *Download URL* value.
+
You can access the backup file through the URL.

. Using a web browser or utility such as Curl, download the backup file to your local workstation with the URL.

.Static IP address assigned to ONTAP Select Deploy

You must assign a static IP address to the ONTAP Select Deploy administration utility. This requirement applies to all ONTAP Select Deploy instances that manage one or more ONTAP Select two-node clusters.


// 2025 Aug 11, ONTAPDOC-2246