---
sidebar: sidebar
permalink: reference_new_ots.html
keywords: new features
summary: There are several new and changed features provided with the current release of ONTAP Select.
---

= What's new in ONTAP Select 9.10.1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several new and changed features provided with the current release of ONTAP Select.

== Enhanced VMware ESXi support

ONTAP Select 9.11.1 includes support for VMware ESXi 7.0 U3C.

== Support for VMware NSX-T

ONTAP Select 9.10.1 has been qualified for VMware NSX-T version 3.1.2. There are no functional issues or deficiencies when using NSX-T with an ONTAP Select single-node Cluster deployed with an OVA file and the ONTAP Select Deploy administration utility.

However, when using NSX-T with an ONTAP Select multi-node cluster, you should note the following requirements and limitations for ONTAP Select 9.11.1:

Network connectivity checker::
The network connectivity checker available through the Deploy CLI fails when it is run against an NSX-T based network.

== KVM hypervisor is no longer supported

The KVM hypervisor is no longer supported.

Beginning with ONTAP Select 9.10.1 and later releases, you were no longer able to create new KVM-based clusters or add KVM-based hosts using the Deploy utility. Further, 9.10.1 was the last release supporting the manageability functions, such as bring online, with existing KVM clusters and hosts.

Then beginning with ONTAP Select 9.11.1 and later releases, all manageability functionality is no longer available for existing KVM clusters and hosts, except the take offline and delete functions.
