---
sidebar: sidebar
permalink: reference_plan_ots_vcenter.html
keywords: plan, planning, vmware vcenter, vcenter server, vcenter
summary: There are several planning requirements related to VMware vCenter you should consider.
---

= VMware vCenter server on ESXi
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You must define a vCenter server account and associate it with a role containing the necessary administrative privileges.

[NOTE]
You also need the fully qualified domain name or IP address of the vCenter server managing the ESXi hypervisor hosts where ONTAP Select is deployed.

== Administrative privileges

The minimum administrative privileges needed to create and manage an ONTAP Select cluster are presented below.

=== Datastore

* Allocate space
* Browse datastore
* Low level file operations
* Update virtual machine files
* Update virtual machine metadata

=== Host

Configuration::

* Network configuration
* System management

Local operations::

* Create virtual machine
* Delete virtual machine
* Reconfigure virtual machine

=== Network

* Assign network

=== Virtual machine

Configuration::

All privileges in the category.

Interaction::

All privileges in the category.

Inventory::

All privileges in the category.

Provisioning::

All privileges in the category.

=== vApp

All privileges in the category.

// 2023-10-02, ONTAPDOC-1204