---
sidebar: sidebar
permalink: ri_api_workflow01.html
keywords: ONTAP Select
summary: xxx
---

= Workflow 1: Creating a single-node evaluation cluster on ESXi
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can deploy a single-node ONTAP Select cluster on a VMware ESXi host managed by vCenter. The cluster is created with an evaluation license.

The cluster creation workflow differs in the following situations:

* The ESXi host is not managed by vCenter (standalone host)
* Multiple nodes or hosts are used within the cluster
* Cluster is deployed in a production environment with a purchased license
* The KVM hypervisor is used instead of VMware ESXi

=== 1. Register vCenter server credential

When deploying to an ESXi host managed by a vCenter server, you must add a credential before registering the host. The Deploy administration utility can then use the credential to authenticate to vCenter.


[cols="15,15,70"*,options="header"]
|===
|Category
|HTTP verb
|Path

|Deploy
|POST
|/security/credentials

|===

Curl::
[source,curl]
curl -iX POST -H 'Content-Type: application/json' -u
admin:admin123 -k -d @step01 'https://10.21.191.150/api/security/
credentials'

JSON input::
[source,json]
{
"hostname": "vcenter.company-demo.com",
"type": "vcenter",
"username": "misteradmin@vsphere.local",
"password": "mypassword"
}

Processing type::
Asynchronous

Output::
* Credential ID in the location response header
* Job object

=== 2. Register a hypervisor host
xxx
