---
sidebar: sidebar
permalink: ri_lic_ontap_features.html
keywords: ONTAP Select
summary: xxx
---

= ONTAP features enabled by default
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
ONTAP Select automatically licenses several features for each node when you deploy a cluster.

[cols="1"]
|===
|*Draft comment:*
ONTAP Select 9.7 RC1 - Need to include TR 1.6 "ONTAP Select feature support"
{set:cellbgcolor:yellow}
|===

Licenses for the following features are included by default:

* NFS
* CIFS
* iSCSI
* FlexClone
* SnapRestore
* SnapVault
* SnapMirror
* Deduplication and compression
* ONTAP multitenancy capability
* NetApp Volume Encryption (non-restricted countries only)

You must purchase a separate license for any other features, including:

* SnapLock Enterprise
* FabricPool
* FlexCache

NOTE: You do not need a FabricPool license when utilizing StorageGRID Webscale.

.Related information

* link:concept_overview.html#comparing-ontap-select-and-ontap-9[Comparing ONTAP Select and ONTAP 9]
