---
sidebar: sidebar
permalink: ri_lic_ontap_features.html
keywords: ONTAP Select
summary: xxx
---

= ONTAP features enabled by default
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
ONTAP Select offers full support for most ONTAP functionality, except those features that have hardware-specific dependencies.

ONTAP Select automatically licenses several features for each node when you deploy a cluster.

===== *Included features*

The following features are included and licensed by default:

* NFS
* CIFS
* iSCSI
* SnapMirror
* SnapVault
* FlexClone
* SnapRestore
* NetApp Volume Encryption

* Deduplication and compression
* ONTAP multitenancy capability
* NetApp Volume Encryption (non-restricted countries only)

===== *Separately licensed features*

You must acquire a separate license for any other features, including:

* SnapLock Enterprise
* FabricPool
* Data Availability Service
* FlexCache (zero cost)
* SyncMirror (zero cost)
* MetroCluster SDS (ONTAP Select premium license offering)

NOTE: You do not need a FabricPool license when utilizing StorageGRID Webscale.

.Related information

* link:concept_overview.html#comparing-ontap-select-and-ontap-9[Comparing ONTAP Select and ONTAP 9]
