---
bar: sidebar
permalink: rt_chk_deploy_req_info.html
keywords: ontap select, deploy, pre-installation, vmware
summary: deploy preparation in a vmware environment
---

= Required information for Deploy utility installation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Before installing the Deploy administration utility in a VMware environment, review the basic requirements and prepare for successful deployment.

== Requirements and restrictions for a deployment

There are several requirements and restrictions to consider when installing the ONTAP Select Deploy utility in a VMware environment.

=== ESXi host server hardware requirements

There are several minimum resource requirements that your ESXi hypervisor host must meet. You should make sure that the hosts where ONTAP Select is deployed meet the following basic requirements:

* ESXi Server:
** Hardware and software must be 64-bit
** Must adhere to the same supported versions as defined for an ONTAP Select node
* Virtual CPUs (2)
* Virtual memory (4 GB)
* Storage (40 GB)
* DHCP enabled (can also assign a static IP address)

=== Network connectivity

You must make sure that the ONTAP Select Deploy virtual machine network interface is configured and has a single management IP address. You can use DHCP to dynamically assign an IP address or manually configure a static IP address.

Depending on your deployment decisions, the Deploy VM must be able to connect to the vCenter server, ESXi hypervisor hosts, and ONTAP Select nodes it manages. You must configure your firewalls to allow the required traffic.

Deploy uses the VMware VIX API to communicate with the vCenter server and ESXi hosts. Initially, it establishes a connection using SOAP over SSL on TCP port 443. After this, a connection is opened using SSL on port 902. In addition, Deploy issues PING commands to verify there is an ESXi host at the IP address you specify.

Deploy must also be able to communicate with the ONTAP Select node and cluster management IP addresses using the following protocols:

* PING command (ICMP)
* SSH (port 23)
* SSL (port 443)

=== Support for IP version 4

ONTAP Select Deploy only supports IP version 4 (IPv4). IP version 6 (IPv6) is not supported. This restriction affects ONTAP Select in the following ways:

* You must assign an IPv4 address to the management LIF of the Deploy virtual machine.
* Deploy cannot create ONTAP Select nodes configured to use IPv6 on the ONTAP LIFs.

=== VMware vCenter language restriction

If you use ONTAP Select Deploy to create a cluster running on ESXi with vCenter on a Windows Server, you must use an English language version. ONTAP Select Deploy does not support vCenter on non-English versions of Windows.

== Required configuration information

As part of your deployment planning, you should determine the required configuration information before installing the ONTAP Select Deploy administration utility.

Name of the Deploy virtual machine::
Identifier to use for the virtual machine.

Name of the ESXi host::
Identifier for the VMware ESXi host where the Deploy utility is installed.

Name of the datastore::
Identifier for the VMware datastore holding the virtual machine files (approximately 40 GB is required).

Network for the virtual machine::
Identifier for the Network where the Deploy virtual machine is connected.

== Optional network configuration information

The Deploy virtual machine is configured using DHCP by default. However, if needed, you can manually configure the network interface for the virtual machine.

Host name::
Identifier of the host machine.

Host IP address::
Static IPv4 address of the host machine.

Subnet mask::
Subnetwork mask, based on the network the virtual machine is a part of.

Gateway::
Default gateway or router.

Primary DNS server::
Primary Domain Name Server.

Secondary DNS server::
Secondary Domain Name Server.

Search domains::
List of the search domains to use.
