---
sidebar: sidebar
permalink: rt_chk_temporary.html
keywords: ontap select
summary: xxx
---

= Host configuration checklist
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Temporary placeholder for IE/TME content.

This content is considered to be a DITA reference and so the file name is *rt_chk_temporary.adoc*.

Assuming there will be multiple checklist files, it is suggested that all of them begin with the same prefix (such as *rt_chk_xxx.adoc*).

This host configuration checklist section should absorb content that was previously owned by IE in the installation guide, including:

Host configuration and preparation checklist chapter::
The entire chapter. Note that the network diagrams need to be reviewed and updated (such as, to align with new four-NIC best practice).

ONTAP Select Deploy planning chapter::
* _Required configuration information_ section
* _Optional network configuration information_ section

ONTAP Select planning chapter::
* _Required information for a VMware deployment_ section
