---
sidebar: sidebar
permalink: rt_chk_select_req_info.html
keywords: ontap select, pre-installation, vmware
summary: As part of preparing to deploy an ONTAP Select cluster in a VMware environment, collect the information required when using the ONTAP Select Deploy administration utility to deploy and configure the cluster.
---

= Required information for ONTAP Select installation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
As part of preparing to deploy an ONTAP Select cluster in a VMware environment, collect the information required when using the ONTAP Select Deploy administration utility to deploy and configure the cluster.

Some of the information you collect applies to the cluster itself, while other information applies to the individual nodes in the cluster.

== Cluster-level information

You must collect information related to the ONTAP Select cluster.

Name of the cluster::
Unique identifier of the cluster.

Licensing mode::
Evaluation or purchased licensing.

IP configuration for the cluster::
IP configuration for the clusters and nodes, including:

* Management IP address of the cluster
* Subnet mask
* Default gateway

== Host-level information

You must collect information related to each of the nodes in the ONTAP Select cluster.

Name of the host::
Unique identifier of the host.

Domain name of the host::
Fully qualified domain name of the host.

IP configuration for the nodes::
Management IP address for each node in the cluster.

Mirror node::
Name of the associated node in the HA pair (multi-node clusters only).

Storage pool::
Name of the storage pool that is used.

Storage disks::
List of disks if using software RAID.

Serial number::
If you are deploying with a purchased license, the unique nine-digit serial number provided by NetApp.

== Access to a vCenter server

You must have access to the vCenter server managing the ESXi hypervisor hosts where ONTAP Select is deployed.

=== Location

You must have the fully qualified domain name or IP address of the vCenter server.

=== Administrative privileges

You must define a vCenter server account and associate it with a role containing the necessary administrative privileges. The following minimum administrative privileges are needed to create and manage an ONTAP Select cluster:

*Datastore*

* Allocate space
* Browse datastore
* Low level file operations
* Update virtual machine files
* Update virtual machine metadata

*Host*

* Configuration
** Change SNMP settings
** Network configuration
** System management
* Local operations
** Create virtual machine
** Delete virtual machine
** Reconfigure virtual machine

*Network*

* Assign network

*Virtual machine*

* Configuration
All privileges in the category
* Interaction
All privileges in the category
* Inventory
All privileges in the category
* Provisioning
All privileges in the category

*vApp*

* All privileges in the category
