---
sidebar: sidebar
permalink: sizing-capacity-pool-license.html
keywords: license, licensing, Capacity Tiers, usable, space
summary: The Capacity Tiers license is based on the underlying disk capacity managed by each node and not the usable capacity of the node, HA-pair, or cluster. Each Capacity Tiers license is assigned to an individual node serial number for a specified capacity and requires an accompanying support contract.
---
= Considerations for sizing an ONTAP Select Capacity Pools license
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The licensed capacity for a Capacity Pool license is in full TB amounts, with a minimum of 2 TB. You calculate the licensed capacity by multiplying the amount of usable space by the overhead factor. The overhead factor differs between a single-node and multi-node (HA-pair based) clusters:

* Overhead factor for single-node clusters is 1.13
* Overhead factor for multi-node clusters is 2.67

You need to calculate the licensed capacity based on the usable space to ensure you have enough for your deployment.

[cols="25,30,45",options="header"]
|===
| Description | Single-node | HA pair or mix of HA and single-node

| Usable space
| 20 TB
| 10 TB per single-node cluster

20 TB for HA pair

| Licensed space
| 23 TB 

(20 x 1.13 = 22.6, round up to next full TB)
| 54 TB 

(20 x 2.67 = 53.4, round up to next full TB)


| Maximum usable space per node

*Note*: The maximum managed space per node or HA pair is 400 TB
|  353 TB 

(400 / 1.13)
a| Per single-node cluster: 

74 TB [(400 / 2) / 2.67]

Per HA pair cluster: 

148 TB (2 x 74)
|===

.What's next

link:task_lic_acquire_cp.html[Acquire a Capacity Pools license for ONTAP Select]

// 2026 FEB 6, ONTAPDOC-3699
// 2026 JAN 27, ONTAPDOC-3021