---
sidebar: sidebar
permalink: sizing-capacity-tier-license.html
keywords: license, licensing, Capacity Tiers, usable, space
summary: The Capacity Tiers license is based on the underlying disk capacity managed by each node and not the usable capacity of the node, HA-pair, or cluster. Each Capacity Tiers license is assigned to an individual node serial number for a specified capacity and requires an accompanying support contract.
---
= Considerations for sizing an ONTAP Select Capacity Tiers license
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Capacity Tiers license is based on the underlying disk capacity managed by each ONTAP Select node and not the usable capacity of the node, HA-pair, or cluster. Each Capacity Tiers license is assigned to an individual node serial number for a specified capacity and requires an accompanying support contract.

The licensed capacity for a Capacity Tiers license is in full TB amounts, with a minimum of 1 TB. You calculate the licensed capacity by multiplying the amount of usable space by the overhead factor. The overhead factor differs between a single-node and multi-node (HA-pair based) clusters:

* Overhead factor for single-node clusters is 1.13
* Overhead factor for multi-node clusters is 2.67

Calculate the licensed capacity based on the usable space to ensure you have enough for your deployment.

[cols="25,30,45",options="header"]
|===
| Description | Single node | HA pair

| Usable space
| 10 TB
| 5 TB per node

10 TB for HA pair

| Licensed space
| 12 TB 

(10 x 1.13 = 11.3, round up to next full TB)
| Two 14 TB licenses 

(5 x 2.67 = 13.35, round up to next full TB)


| Maximum usable space per node

*Note*: The maximum managed space per node or HA pair is 400 TB
|  353 TB 

(400 / 1.13)
a| Per node in a HA pair:

* 74 TB [(400 / 2) / 2.67]

Per HA pair in a multi-node cluster:

* Two-node: 148 TB (2 x 74)
* Four-node: 296 TB (4 x 74)
* Six-node: 444 TB (6 x 74)
* Eight-node: 592 TB (8 x 74)
|===

.What's next
link:task_lic_acquire_ct.html[Acquire a Capacity Tier license for ONTAP Select]

// 2026 FEB 6, ONTAPDOC-3699
// 2026 JAN 27, ONTAPDOC-3021