---
sidebar: sidebar
permalink: task_cli_migrate_deploy.html
keywords: administer, administering, cli, deploy, deploy instance, migrate
summary: You can migrate an existing instance of the Deploy administration utility to a new virtual machine using the command line interface.
---

= Migrating a Deploy instance to a new virtual machine
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can migrate an existing instance of the Deploy administration utility to a new virtual machine using the command line interface.

== Before you begin

This procedure is based on creating a new virtual machine that uses the configuration data from the original virtual machine. The new and original virtual machines must run the same version and release of the Deploy utility. You cannot migrate to a different version and release of the Deploy utility.

At a high level, the process used to migrate a Deploy instance to a new virtual machine consists of three steps:

. Backing up the Deploy configuration data
. Installing a new instance of the Deploy virtual machine
. Restore the Deploy configuration data to the new virtual machine

You should be familiar with the procedures used to download and deploy the ONTAP Select Deploy virtual machine in a VMware environment.

== Backing up the Deploy configuration data

xxx
