---
sidebar: sidebar
permalink: task_api_understanding_call.html
keywords: rest api, deploy rest api, rest, understanding, executing
summary: The details of all the API calls are documented and displayed using a common format on the ONTAP Select Deploy online documentation web page. By understanding a single API call, you can access and interpret the details of all the API calls.
---

= Understand and execute an API call
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The details of all the API calls are documented and displayed using a common format on the ONTAP Select Deploy online documentation web page. By understanding a single API call, you can access and interpret the details of all the API calls.

.Before you begin

You must be signed in to the ONTAP Select Deploy online documentation web page. You must have the unique identifier assigned to your ONTAP Select cluster when the cluster was created.

.About this task

You can retrieve the configuration information describing an ONTAP Select cluster using its unique identifier. In this example, all fields classified as inexpensive are returned. However, as a best practice you should request only the specific fields that are needed.

.Steps

. On the main page, scroll to the bottom and click *Cluster*.

. Click *GET /clusters/{cluster_id}* to display the details of the API call used to return information about an ONTAP Select cluster.
