---
sidebar: sidebar
permalink: task_cli_deploy_image_remove.html
keywords: administer, administering, cli, deploy, ontap select image, remove
summary: You can remove ONTAP Select images from your instance of the Deploy administration utility when they are no longer needed.
---

= Remove an ONTAP Select image from Deploy
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can remove ONTAP Select images from your instance of the Deploy administration utility when they are no longer needed.

[CAUTION]
You should not remove any ONTAP Select images that are in use by a cluster.

.About this task

You can remove older ONTAP Select images that are not currently in use by a cluster or planned for use with a future cluster deployment.

.Steps

. Sign in to the Deploy utility CLI using SSH with the administrator (admin) account.

. Display the clusters managed by Deploy and record the ONTAP images in use:
+
`cluster show`
+
Note the version number and hypervisor platform in each case.

. Start the Bash shell:
+
`shell bash`

. Display all of the available ONTAP Select images:
+
`ls -lh /opt/netapp/images`

. Optionally remove an ESXi image.
+
Example
`rm -r /opt/netapp/images/DataONTAPv-9.3RC1-vidconsole-esx.ova`

. Optionally remove a KVM image when using a release earlier than ONTAP Select 9.10.1.
+
Example
`rm -r /opt/netapp/images/DataONTAPv-9.3RC1-serialconsole-kvm.raw.tar`
