---
sidebar: sidebar
permalink: task_cluster_expansion_contraction.html
keywords: cluster, expand, expansion, contract, contraction, six, eight, node deployment workflow, workflow, deployment steps
summary: Beginning with ONTAP Select 9.15.1, you can increase the size of an existing cluster from six to eight nodes and decrease the cluster size from eight to six nodes.
---
= Expand or contract an ONTAP Select ESXi or KVM cluster
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can increase the cluster size of an existing ONTAP Select cluster for ESXi and KVM hypervisor hosts. For KVM hosts, you can increase the cluster size from six to eight nodes and decrease the size from eight to six nodes. For ESXi hosts, you increase and decrease the cluster size in increments between six and twelve nodes. 

The following cluster expansions and contractions aren't supported for ESXi and KVM hosts:

* Expansions from one, two, or four-node clusters to six or eight-node clusters.
* Contractions from six or eight-node clusters to one, two, or four-node clusters.

[NOTE]
====
To change the number of nodes in a cluster to a size that isn't supported by cluster expansion or contraction, you need to perform the following tasks:

. Deploy a new multi-node cluster by using the link:task_cli_deploy_cluster.html[CLI] or the link:task_deploy_cluster.html[web UI] provided with the ONTAP Select Deploy administration utility.
. If applicable, migrate the data to the new cluster by using link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html[SnapMirror replication^].
====

You initiate the cluster expansion and contraction procedures from ONTAP Select Deploy using the CLI, API, or web interface.

== Hardware and storage considerations
The cluster expansion and contraction feature is supported on the following KVM and ESXi hypervisor hosts.

[role="tabbed-block"]
====
.ESXi
--
Beginning with ONTAP Select 9.15.1, cluster expansion and contraction is supported on ESXi hypervisor hosts. 

Cluster expansion and contraction is supported for the following ESXi hypervisor versions:

* ESXi 9.0
* ESXi 8.0 U3
* ESXi 8.0 U2 
* ESXi 8.0 U1
* ESXi 8.0 GA 
* ESXi 7.0 U3
* ESXi 7.0
--
.KVM
--
Beginning with ONTAP Select 9.17.1, cluster expansion and contraction is supported on KVM hypervisor hosts.

Cluster expansion and contraction is supported for the following KVM hypervisor versions:

* Red Hat Enterprise Linux 64-bit 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.8, 8.7, and 8.6
* Rocky Linux 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7, and 8.6
--

====

== Expand the cluster
Use the cluster expansion feature to increase the size of an existing ESXi or KVM cluster.

[role="tabbed-block"]
====
.ESXi
--
You can increase the size of an existing ESXi cluster in the following increments:

* From six nodes to eight, ten, or twelve nodes
* From eight nodes to ten or twelve nodes
* From ten to twelve nodes 
--
.KVM
--
You can increase the size of an existing KVM cluster from six to eight nodes.
--
====

.About this task
In preparation for cluster expansion, new ESXi and KVM hosts are added to the inventory and the details of the new nodes are assigned. Before starting the cluster expansion process, a network precheck verifies the selected internal network.

.Before you begin
* When deploying a multi-node cluster, you should be familiar with the network connectivity checker. You can run the network connectivity checker using the link:task_adm_connectivity.html[web UI] or the link:task_cli_connectivity.html[CLI].

* Verify that you have the license details for the new nodes. 

.Steps
. Sign in to the Deploy utility web user interface using the administrator account.

. Select the *Cluster* tab at the top of the page and select the desired cluster from the list.

. On the cluster details page, select the gear icon at the right of the page and select *Expand Cluster*.

. Navigate to the *HA Pair 4* section.

. Choose the following high availability (HA) pair configuration details for the fourth HA pair: 
* Instance type
* Node names 
* Associated hypervisor hosts 
* Node IP addresses 
* Licenses 
* Networking configuration 
* Storage configuration (RAID type and storage pools)

. Select *Save HA Pair* to save the configuration details.

. Provide the ONTAP credentials, and select *Expand Cluster*.

. Select *Next* and run the network pre-check by selecting *Run*. 
+
The network pre-check validates that the internal network selected for the ONTAP cluster traffic is functioning correctly.

. Select *Expand Cluster* to begin the cluster expansion process, and then select *OK* in the dialog box.
+
It can take up to 45 minutes for the cluster to be expanded.

. Monitor the multi-step cluster expansion process to confirm that the cluster expanded successfully.

. Refer to the *Events* tab for periodic updates on the operation's progress. The page is automatically refreshed at regular intervals.

.After you finish
After expanding the cluster, you should back up the ONTAP Select Deploy configuration data.

== Contract the cluster
Use the cluster contraction feature to decrease the size of an existing ESXi or KVM cluster.

[role="tabbed-block"]
====
.ESXi
--
You can decrease the size of an existing ESXi cluster in the following increments:

* From twelve nodes to ten, eight, or six nodes 
* From ten nodes to eight or six nodes
* From eight to six nodes 
--
.KVM
--
You can decrease the size of an existing cluster from eight to six nodes.
--
====

.About this task
The desired HA pair of nodes in the cluster are selected to prepare for cluster contraction during the procedure.

.Steps
. Sign in to the Deploy utility web user interface using the administrator account.

. Select the *Cluster* tab at the top of the page and select the desired cluster from the list.

. On the cluster details page, select the gear icon at the right of the page, then select *Contract Cluster*.

. Select the HA Pair configuration details for any HA Pair you want to remove and provide the ONTAP credentials, then select *Contract Cluster*.
+
It can take up to 30 minutes for the cluster to be contracted.

. Monitor the multi-step cluster contraction process to confirm that the cluster contracted successfully.

. Refer to the *Events* tab for periodic updates on the operation's progress. The page is automatically refreshed at regular intervals.


// 2025 Sep 02, ONTAPDOC-9.17.1GA
// 2025 AUG 19, ONTAPDOC-3002
// 2025 JUN 20, ONTAPDOC-2886
// 2024 NOV 5, ONTAPDOC-2518
// 2023 May 06, ONTAPDOC-1797, -1802