---
sidebar: sidebar
permalink: task_cluster_expansion_contraction.html
keywords: cluster, expand, expansion, contract, contraction, six, eight, node deployment workflow, workflow, deployment steps
summary: Beginning with ONTAP Select 9.15.1, you can increase the size of an existing cluster from six to eight nodes and decrease the cluster size from eight to six nodes.
---

= Expand or contract the cluster
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with ONTAP Select 9.15.1, you can increase the size of an existing cluster from six to eight nodes and decrease the cluster size from eight to six nodes. No other cluster expansion or contraction scenarios are supported.

The procedure is initiated from ONTAP Select Deploy using the CLI, API, or web interface.

== Hardware and storage requirements
The cluster expansion and contraction functionalities are restricted in the following ways:

* Support is limited to clusters created on ESX hypervisor hosts. The following ESX versions are compatible with ONTAP Select 9.15.1:
** ESXi 8.0U2 
** ESXi 8.0U1
** ESXi 8.0GA 
** ESXi 7.0U3
** ESXi 7.0

* Expansion is only possible from six-node clusters to eight-node clusters.
* Contraction is only possible from eight-node clusters to six-node clusters.

== Expand the cluster
You can increase the size of an existing cluster from a six-node to an eight-node cluster with the cluster expansion feature.

.About this task
In preparation for the cluster expansion procedure, new ESX hosts are added to the inventory and the details of the new nodes are assigned. Before starting the cluster expansion process, a network precheck verifies the selected internal network.

.Before you begin
* When deploying a multi-node cluster, you should be familiar with the link:https://docs.netapp.com/us-en/ontap-select/task_adm_connectivity.html[network connectivity checker]. 

* Verify that you have the license details for the new nodes. 

.Steps
. Sign in to the Deploy utility web user interface using the administrator account.

. Select the *Cluster* tab at the top of the page and select the desired cluster from the list.

. On the cluster details page, select the gear icon at the right of the page and select *Expand Cluster*.

. Navigate to the *HA Pair 4* section.

. Choose the high-availability (HA) pair configuration details for the fourth HA pair, including: 
* Instance type
* Node names 
* Associated hypervisor hosts 
* Node IP addresses 
* Licenses 
* Networking configuration 
* Storage configuration (RAID type and storage pools)

. Select *Save HA Pair* to save the configuration details.

. Provide the ONTAP credentials, then select *Expand Cluster*.

. Select *Next* and run the network pre-check by selecting *Run*. 
+
The network pre-check validates that the internal network selected for the ONTAP cluster traffic is functioning correctly.

. Select *Expand Cluster* to begin the cluster expansion process, and then select *OK* in the dialog box.
+
It can take up to 45 minutes for the cluster to be expanded.

. Monitor the multi-step cluster expansion process to confirm that the cluster expanded successfully.

. Refer to the *Events* tab for periodic updates on the operation's progress. The page is automatically refreshed at regular intervals.

.After you finish
After expanding the cluster, you should back up the ONTAP Select Deploy configuration data.

== Contract the cluster
You can decrease the size of an existing cluster from an eight-node to a six-node cluster with the cluster contraction feature.

.About this task
The desired HA pair of nodes in the cluster are selected to prepare for cluster contraction during the procedure.

.Steps
. Sign in to the Deploy utility web user interface using the administrator account.

. Select the *Cluster* tab at the top of the page and select the desired cluster from the list.

. On the cluster details page, select the gear icon at the right of the page, then select *Contract Cluster*.

. Select the HA Pair configuration details for any HA Pair you want to remove and provide the ONTAP credentials, then select *Contract Cluster*.
+
It can take up to 30 minutes for the cluster to be contracted.

. Monitor the multi-step cluster contraction process to confirm that the cluster contracted successfully.

. Refer to the *Events* tab for periodic updates on the operation's progress. The page is automatically refreshed at regular intervals.

// 2023 May 06, ONTAPDOC-1797, -1802