---
sidebar: sidebar
permalink: task_cli_deploy_recover_two_node.html
keywords: administer, administration, cli, two node cluster, recover
summary: If the ONTAP Select Deploy utility fails or becomes unavailable for some reason, you lose the ability to administer ONTAP Select nodes and clusters. In addition, all two-node clusters lose HA capability because the mediator service included with Deploy is unavailable. If an unrecoverable failure occurs, you must recover the Deploy utility instance to restore administrative and HA functionality.
---

= Recovering the Deploy utility for a two-node cluster
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If the ONTAP Select Deploy utility fails or becomes unavailable for some reason, you lose the ability to administer ONTAP Select nodes and clusters. In addition, all two-node clusters lose HA capability because the mediator service included with Deploy is unavailable. If an unrecoverable failure occurs, you must recover the Deploy utility instance to restore administrative and HA functionality.

== Before you begin

You should prepare before attempting to recover an instance of the Deploy utility to assure success.

===== *Required skills and information*

You should be familiar with several administrative procedures and have the required information.

===== *Installing the Deploy virtual machine*

You must be able to install a new instance of the ONTAP Select Deploy utility in your hypervisor environment.

===== *ONTAP command line interface*

You must be able to sign in to the ONTAP CLI of the ONTAP Select cluster and use the shell interface.

===== *Availability of Deploy utility configuration backup*

You must determine if you have a backup of the configuration data from the failed Deploy utility instance that contains the ONTAP Select two-node cluster. You might have a backup that does not contain the cluster.

===== *Restoring a backup of the Deploy configuration*

You should be able to restore a backup of the Deploy configuration data, depending on the recovery procedure used.

===== *IP address of the original Deploy virtual machine*

You must know the IP address of the original Deploy utility virtual machine that failed.

===== *Storage capacity licensing*

You must determine whether capacity pools or capacity tiers licensing is used. If you use capacity pools licensing, you must reinstall each capacity pool license after recovering or restoring the Deploy instance.

===== *Deciding which recovery procedure to use*
You must decided which procedure to use when recovering an instance of the ONTAP Select Deploy utility. Your decision is based on whether or not you have a backup of the configuration data from the original failed Deploy utility that contains the ONTAP Select two-node cluster.

[cols="20,80"*,options="header"]
|===

|Do you have a Deploy backup containing the two-node cluster?
|Recovery procedure to use

|Yes
|Restoring a Deploy utility instance using a configuration backup

|No
|Reconfiguring and recovering a Deploy utility instance

|===

== Restoring a Deploy utility instance using a configuration backup

If you have a backup of the failed Deploy utility instance containing the two-node cluster, you can restore the configuration data to the new Deploy virtual machine instance. You must then complete the recovery by performing additional configuration of the two nodes in the ONTAP Select cluster.

.Before you begin

You must have a backup of the configuration data from the original failed Deploy virtual machine that contains the two-node cluster. You must be able to sign in to the ONTAP CLI of the two-node cluster and know the ONTAP names of the two nodes.

.About this task

Because the configuration backup you restore contains the two-node cluster, the mediator iSCSI targets and mailboxes are recreated in the new Deploy utility virtual machine.

.Steps

. Prepare a new instance of the ONTAP Select Deploy utility:
.. Install a new Deploy utility virtual machine.
.. Restore the Deploy configuration from a previous backup to the new virtual machine.
+
Refer to the related tasks for more detailed information about the install and restore procedures.

. Sign in to the ONTAP command line interface of the ONTAP Select two-node cluster.

. Enter advanced privilege mode:
+
`set adv`

. If the IP address of the new Deploy virtual machine is different than the original Deploy virtual machine, you must remove the old mediator iSCSI targets and add new targets:
.. `storage iscsi-initiator remove-target -node * -target-type mailbox`
.. `storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>`
.. `storage iscsi-initiator add-target -node <node2_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>`
+
The _<ip_address>_ parameter is the IP address of the new Deploy virtual machine.
+
These commands allow the ONTAP Select nodes to discover the mailbox disks on the new Deploy utility virtual machine.

. Determine the names of the mediator disks:
+
`disk show --container-type mediator`

. Assign the mailbox disks to the two nodes:
+
.. `disk assign -disk <mediator-disk1-name> -owner <node1-name>``
.. `disk assign -disk <mediator-disk2-name> -owner <node2-name>`

. Verify that storage failover is enabled:
+
`storage failover show`

.After you finish

If you use capacity pools licensing, you must reinstall each capacity pool license. See _Reinstalling a capacity pool license_ for additional details.

*MUST COMPLETE*
