---
sidebar: sidebar
permalink: task_lic_acquire_cp.html
keywords: license, licensing, acquire, Capacity Pools
summary: You must acquire a license file for each Capacity Pool used by the ONTAP Select nodes. The license file defines the storage capacity and expiration for the pool. It is locked to the License Manager through a combination of the unique license serial number assigned by NetApp and the License Lock ID associated with the Deploy instance.
---
= Acquire an ONTAP Select Capacity Pool license
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You must acquire a license file for each Capacity Pool used by the ONTAP Select nodes. The license file defines the storage capacity and expiration for the pool. It is locked to the License Manager through a combination of the unique license serial number assigned by NetApp and the License Lock ID associated with the Deploy instance.

.Before you begin

* You must have the nine-digit license serial number assigned to the Capacity Pool by NetApp. 
* You should wait at least 24 hours after the shipped date of your purchase order before acquiring a license file.
* You have reviewed the link:sizing-capacity-pool-license.html[considerations for sizing a Capacity Pools license].

.About this task

You must perform this task for each Capacity Pool used by the ONTAP Select nodes.

.Steps

. Log in to the link:https://mysupport.netapp.com/site/[NetApp Support site^].

. Select *Systems* > *Software Licenses*.

. Type the license serial number for the Capacity Pool and select *Go!*.

. On the license details page, navigate to the *Product Details* column.

. Select *Get NetApp License File* on the appropriate row.

. Type the License Lock ID for your ONTAP Select Deploy instance and select *Submit*.

. Select the appropriate delivery method and select *Submit*.

. Select *OK* on the delivery confirmation window.

.After you finish

You must upload the license file to the Deploy administration utility before an ONTAP Select node can use the Capacity Pool.
