---
sidebar: sidebar
permalink: task_cli_upgrade_deploy.html
keywords: administer, administering, cli, deploy, upgrade deploy
summary: You can upgrade an existing Deploy utility virtual machine in-place using the command line interface.
---

= Upgrade a Deploy instance
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can upgrade an existing Deploy utility virtual machine in-place using the command line interface.

== Before you begin

Make sure that Deploy is not used to perform any other tasks during the upgrade. You should see the current release notes for information and restrictions about upgrading the Deploy utility.

[NOTE] 
If you have an older instance of the ONTAP Select Deploy administration utility installed, you should upgrade to the current release. The ONTAP Select node and ONTAP Select Deploy component are upgraded independently. See link:concept_adm_upgrading_nodes.html[Upgrade the ONTAP Select nodes^] for further details.

== Download the upgrade package

To begin the upgrade process, you must download the appropriate Deploy virtual machine upgrade file from the NetApp Support Site. The upgrade package is formatted as a single compressed file.

.Steps

. Access the link:https://mysupport.netapp.com/site/[NetApp Support Site^] using a web browser and choose *Downloads* from the Downloads menu.

. Scroll down and select *ONTAP Select Deploy Upgrade*.

. Select the desired release of the upgrade package.

. Review the End User License Agreement (EULA) and select *Accept & Continue*.

. Select and download the appropriate package, responding to all prompts as needed for your environment.

== Upload the package to the Deploy virtual machine

After acquiring the upgrade package, you must upload the file to the Deploy virtual machine.

.Before you begin

You must have the upgrade file available on your local workstation. You must also have the password for the administrator user account.

.About this Tasks

This task describes one method for uploading the file to the Deploy virtual machine. There may be other options more suitable for your environment.

.Steps

. In a command shell on your local workstation, use the scp utility to upload the image file to the Deploy virtual machine.
+
Example
+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....

.Result
The upgrade file is stored in the home directory of the admin user.


== Apply the upgrade package

After the upgrade file has been uploaded to the Deploy virtual machine, you can apply the upgrade.

.Before you begin
You must known which directory the upgrade file has been placed in at the Deploy utility virtual machine. Also, assure that Deploy is not used to perform any other tasks while the upgrade is performed.

.Steps

. Sign in to the Deploy utility CLI using SSH with the administrator account.
. Perform the upgrade using the appropriate directory path and file name:
+
`deploy upgrade -package-path FILEPATH`
+
Example
+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....

.After you finish

Before the upgrade procedure completes, you are asked to create a backup of the Deploy virtual machine configuration. Also, you should clear the browser cache so you can view the newly created Deploy pages.

// 2023-06-06, github issue #178
// 2023-10-17, prep for repo version split
// 2023-11-01, github issue #221