---
sidebar: sidebar
permalink: task_vpi_adm_clusters.html
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, administer, administering, clusters
summary: There are several related tasks you can perform to administer an ONTAP Select cluster.
---

= ONTAP Select clusters
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several related tasks you can perform to administer an ONTAP Select cluster.

== Move an ONTAP Select cluster to the offline and online states

After you have created a cluster, you can change its status to offline or online as needed.

.Steps

. Click *ONTAP Select Clusters* in the *Global Inventory Lists* pane.

. Right click the desired cluster to display the available actions.

. Click *Take Offline* or *Bring Online* as appropriate and click *Yes* to confirm the request.

== Delete an ONTAP Select cluster

You can delete an ONTAP Select cluster when it is no longer needed.

.Before you begin

The cluster must be in the offline state.

.Steps

. Click *ONTAP Select Clusters* in the *Global Inventory Lists* pane.

. Right click the desired cluster to display the available actions.

. Click *Delete Cluster* and click *Yes* to confirm the request.
+
If the delete option is not available, then the cluster is not in an offline state.
