---
sidebar: sidebar
permalink: task_adm_resize.html
keywords: administer, administering, web, resizing nodes, resizing
summary: After deploying an ONTAP Select cluster, you can upgrade the hypervisor instance type of the nodes using the Deploy administration utility.
---

= Resize the ONTAP Select cluster nodes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After deploying an ONTAP Select cluster, you can upgrade the hypervisor instance type of the nodes using the Deploy administration utility.

[NOTE]
You can perform the cluster nodes resizing operation when using the capacity tiers licensing model and the capacity pools licensing model.

[NOTE]
Resizing to the large instance type is only supported on ESXi.

.Before you begin

The cluster must be in the online state.

.About this task

This task describes how to use the Deploy web user interface. You can also use the Deploy CLI to perform the instance resizing. Regardless of which interface you use, the time needed for the resizing operation can vary significantly based on several factors and may take an extended amount of time to complete. You can only resize a node to a larger size.

.Steps

. Sign in to the Deploy utility web user interface using the administrator account.

. Click the *Cluster* tab at the top of the page and select the desired cluster from the list.

. On the cluster details page, click the gear icon at the right of the page and select *Instance Resize*.

. Select the *Instance Type* and provide the ONTAP credentials then click *Modify*.

.After you finish

You must wait for the resize operation to complete.

// 2023-07-11, ONTAPDOC-1136
// 2024-03-18, ONTAPDOC-1692