---
sidebar: sidebar
permalink: task_lic_acquire_cp.html
keywords: license, licensing, acquire, capacity pools
summary: You must acquire a license file for each capacity pool used by the ONTAP Select nodes. The license file defines the storage capacity and expiration for the pool. It is locked to the License Manager through a combination of the unique license serial number assigned by NetApp and the License Lock ID associated with the Deploy instance.
---

= Acquire a capacity pool license
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You must acquire a license file for each capacity pool used by the ONTAP Select nodes. The license file defines the storage capacity and expiration for the pool. It is locked to the License Manager through a combination of the unique license serial number assigned by NetApp and the License Lock ID associated with the Deploy instance.

.Before you begin

You must have the nine-digit license serial number assigned to the capacity pool by NetApp. Before attempting to acquire a license file, you should wait at least twenty four hours after the shipped date of your purchase order.

.About this task

You must perform this task for each capacity pool used by the ONTAP Select nodes.

.Steps

. Access the NetApp Support Site using a web browser and sign in.

. Click *Systems* at the top and then click *Software Licenses*.

. Type the license serial number for the capacity pool and click *Go!*.

. On the license details page, navigate to the *Product Details* column.

. Click *Get NetApp License File* on the appropriate row.

. Type the License Lock ID for your ONTAP Select Deploy instance and click *Submit*.

. Select the appropriate delivery method and click *Submit*.

. Click *OK* on the delivery confirmation window.

.After you finish

You must upload the license file to the Deploy administration utility before the capacity pool can be used by an ONTAP Select node.
