---
sidebar: sidebar
permalink: task_cli_clusters.html
keywords: administer, administering, cli, clusters
summary: There are several related tasks you can perform to administer an ONTAP Select cluster.
---
= Manage ONTAP Select clusters using the CLI
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several related tasks you can perform to administer an ONTAP Select cluster using the CLI.

== Back up the ONTAP Select Deploy configuration data

Backup of the ONTAP Select Deploy configuration data, for example, after deploying a cluster. The data is saved to a single encrypted file that you can download to your local workstation.

The backup file you create captures all the configuration data. This data describes aspects of your deployment environment, including the ONTAP Select clusters.

.Before you begin
Make sure that Deploy is not performing any other tasks during the backup operation.

.Steps

. Sign in to the ONTAP Select Deploy utility CLI using SSH with the administrator account.

. Create a backup of the ONTAP Select Deploy configuration data, which is stored in an internal directory at the ONTAP Select Deploy server:
+
[source,cli]
----
deploy backup create
----

. Provide a password for the backup when prompted.
+
The backup file is encrypted based on the password.

. Display the available backups in the system:
+
[source,cli]
----
deploy backup show -detailed
----

. Select your backup file based on the date in the *Created* field and record the *Download URL* value.
+
You can access the backup file through the URL.

. Using a web browser or utility such as Curl, download the backup file to your local workstation with the URL.

== Delete an ONTAP Select cluster

You can delete an ONTAP Select cluster when it is no longer needed.

.Before you begin

The cluster must be in the offline state.

.Steps

. Sign in to the Deploy virtual machine CLI using the administrator account.

. Display the cluster status:
+
[source,cli]
----
cluster show -name <cluster_name>
----

. If the cluster is not offline, move it to an offline state:
+
[source,cli]
----
cluster offline -name <cluster_name>
----

. After confirming the cluster is in an offline status, delete the cluster:
+
[source,cli]
----
cluster delete -name <cluster_name>
----

// 2025 OCT 22, ONTAPDOC-2246