---
sidebar: sidebar
permalink: task_vpi_adm_network.html
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, administer, administering, network, networking
summary: There are several aspects of the network that you can explore and display.
---

= Confirm network connectivity
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several aspects of the network that you can explore and display.

== Confirm network connectivity

You can test the network connectivity among two or more ONTAP Select nodes on the internal cluster network. You should typically run this test before a multi-node cluster is deployed to detect issues that might cause the operation to fail. You can also run the connectivity test after a cluster is deployed and online.

.About this task

Each time you start the test, a new process is created in the background and assigned a unique run identifier. Only one run can be active at a time.

The test is always run in quick mode which performs a basic nondisruptive test. A PING test is performed, along with a test of the network MTU size and the vSwitch.

.Steps

. Click *ONTAP Select Deploy* in the *Global Inventory Lists* pane.

. Click the *Administration* tab.

. Expand the *Network* option and click *Connectivity Checker*.

. Click *Run New* to start the test.

. Optionally, click *Filtering* and create a filter to limit the test details that are displayed.

== View the status of the mediator service

Each ONTAP Select two-node cluster is monitored by the mediator service, which assists in managing the HA capability shared by the nodes. You can view the status of the mediator service for each of the two-node clusters defined in the Deploy administration utility.

.About this task

You can view the configuration of each mediator, including:

* Current status
* Two ONTAP Select nodes
* iSCSI target where the HA control information is stored

.Steps

. Click *ONTAP Select Deploy* in the *Global Inventory Lists* pane.

. Click the *Administration* tab.

. Expand the *Mediator* option and click *Status*.

. Optionally, click *Filtering* and create a filter to customize your view of the two-node clusters monitored by the mediator service.
