---
sidebar: sidebar
permalink: task_cluster_expansion_contraction.html
keywords: cluster, expand, expansion, contract, contraction, six, eight, node deployment workflow, workflow, deployment steps
summary: Beginning with ONTAP Select 9.15.1, you can increase the size of an existing cluster from six to eight nodes and decrease the cluster size from eight to six nodes.
---
= Expand or contract an ONTAP Select cluster
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with ONTAP Select 9.15.1, you can increase the size of an existing cluster from six to eight nodes and decrease the cluster size from eight to six nodes. 

The following cluster expansions and contractions aren't supported:

* Expansions from one, two, or four-node clusters to six or eight-node clusters.
* Contractions from six or eight-node clusters to one, two, or four-node clusters.

[NOTE]
====
To change the number of nodes in a cluster to a size that isn't supported by cluster expansion or contraction, you need to perform the following tasks:

. Deploy a new multi-node cluster by using the link:task_cli_deploy_cluster.html[CLI] or the link:task_deploy_cluster.html[web UI] provided with the ONTAP Select Deploy administration utility.
. If applicable, migrate the data to the new cluster by using link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html[SnapMirror replication^].
====

You initiate the cluster expansion and contraction procedures from ONTAP Select Deploy using the CLI, API, or web interface.

== Hardware and storage considerations
The cluster expansion and contraction functionalities are restricted in the following ways:

* Support is limited to clusters created on ESX hypervisor hosts. The following ESX versions are compatible with ONTAP Select 9.15.1 and later:
** ESXi 8.0 U3
** ESXi 8.0 U2 
** ESXi 8.0 U1
** ESXi 8.0 GA 
** ESXi 7.0 U3
** ESXi 7.0

== Expand the cluster
You can increase the size of an existing cluster from a six-node to an eight-node cluster with the cluster expansion feature.

.About this task
In preparation for the cluster expansion procedure, new ESX hosts are added to the inventory and the details of the new nodes are assigned. Before starting the cluster expansion process, a network precheck verifies the selected internal network.

.Before you begin
* When deploying a multi-node cluster, you should be familiar with the network connectivity checker. You can run the network connectivity checker using the link:task_adm_connectivity.html[web UI] or the link:task_cli_connectivity.html[CLI].

* Verify that you have the license details for the new nodes. 

.Steps
. Sign in to the Deploy utility web user interface using the administrator account.

. Select the *Cluster* tab at the top of the page and select the desired cluster from the list.

. On the cluster details page, select the gear icon at the right of the page and select *Expand Cluster*.

. Navigate to the *HA Pair 4* section.

. Choose the high availability (HA) pair configuration details for the fourth HA pair, including: 
* Instance type
* Node names 
* Associated hypervisor hosts 
* Node IP addresses 
* Licenses 
* Networking configuration 
* Storage configuration (RAID type and storage pools)

. Select *Save HA Pair* to save the configuration details.

. Provide the ONTAP credentials, then select *Expand Cluster*.

. Select *Next* and run the network pre-check by selecting *Run*. 
+
The network pre-check validates that the internal network selected for the ONTAP cluster traffic is functioning correctly.

. Select *Expand Cluster* to begin the cluster expansion process, and then select *OK* in the dialog box.
+
It can take up to 45 minutes for the cluster to be expanded.

. Monitor the multi-step cluster expansion process to confirm that the cluster expanded successfully.

. Refer to the *Events* tab for periodic updates on the operation's progress. The page is automatically refreshed at regular intervals.

.After you finish
After expanding the cluster, you should back up the ONTAP Select Deploy configuration data.

== Contract the cluster
You can decrease the size of an existing cluster from an eight-node to a six-node cluster with the cluster contraction feature.

.About this task
The desired HA pair of nodes in the cluster are selected to prepare for cluster contraction during the procedure.

.Steps
. Sign in to the Deploy utility web user interface using the administrator account.

. Select the *Cluster* tab at the top of the page and select the desired cluster from the list.

. On the cluster details page, select the gear icon at the right of the page, then select *Contract Cluster*.

. Select the HA Pair configuration details for any HA Pair you want to remove and provide the ONTAP credentials, then select *Contract Cluster*.
+
It can take up to 30 minutes for the cluster to be contracted.

. Monitor the multi-step cluster contraction process to confirm that the cluster contracted successfully.

. Refer to the *Events* tab for periodic updates on the operation's progress. The page is automatically refreshed at regular intervals.



// 2024 NOV 5, ONTAPDOC-2518
// 2023 May 06, ONTAPDOC-1797, -1802