---
sidebar: sidebar
permalink: task_cluster_expansion_contraction.html
keywords: cluster, expand, expansion, contract, contraction, six, eight, node deployment workflow, workflow, deployment steps
summary: Use Ansible roles to automate ONTAP Select deployments.
---

= Expand or contract the cluster
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with ONTAP Select 9.15.1, you can increase the size of an existing cluster from a six-node cluster to an eight-node cluster with the cluster expansion feature, and you can decrease the cluster size from an eight-node cluster to a six-node cluster with the cluster contraction feature.

The procedure is initiated from ONTAP Select Deploy using the CLI, API, or web interface..

== Hardware and storage requirements
The cluster expansion and contraction functionalities are restricted in the following ways:

* Support is limited to clusters created on ESX hypervisor hosts only. The following ESX versions are compatible with ONTAP Select 9.15.1:
** ESXi 8.0u2 
** ESXi 8.0u1
** ESXi 8.0GA 
** ESXi 7.0u3
** ESXi 7.0

* Expansion is only possible from 6 node clusters to 8 node clusters.
* Contraction is only possible from 8 node clusters to 6 node clusters.
* The ONTAP version of the cluster must be 9.15.1+.

== Expand the cluster
You can increase the size of an existing cluster from a six-node cluster to an eight-node cluster with the cluster expansion feature

.About this task
The following tasks occur during the cluster expansion procedure:

* New ESX hosts are added to the inventory.
* The details of the new nodes are assigned to prepare for cluster expansion.

.Before you begin
If you deploy a multi-node cluster, you should be familiar with the link:https://docs.netapp.com/us-en/ontap-select/concept_nw_internal_external.html#internal-network-validation-and-troubleshooting[network connectivity checker]. 

You should also have the license details for the creation of new nodes.

.Steps
. Sign in to the Deploy utility web user interface using the administrator account.

. Select the *Cluster* tab at the top of the page and select the desired cluster from the list.

. On the cluster details page, select the gear icon at the right of the page and select *Expand Cluster*.

. Navigate to the *HA Pair 4* section.

. Choose the high-availability (HA) pair configuration details for the 4th HA pair, including: 
* Instance type
* Node names 
* Associated hypervisor hosts 
* Node IP addresses 
* Licenses 
* Networking configuration 
* Storage configuration (RAID type and storage pools)

. Select *Save HA Pair* to save the configuration details.

. Provide the ONTAP credentials then select *Expand Cluster*.

. Select *Next* and run the network pre-check by selecting *Run*. 
+
The network pre-check validates that the internal network selected for the ONTAP cluster traffic is functioning correctly.

. Select *Expand Cluster* to begin the cluster expansion process and then select *OK* in the dialog box.
+
It can take up to 45 minutes for the cluster to be created.

. Monitor the multi-step cluster expansion process to confirm that the cluster expanded successfully.

. Refer to the events tab for periodic updates on the operation's progress. The page is automatically refreshed at regular intervals.

.After you finish
After expanding the cluster, you should back up the ONTAP Select Deploy configuration data.

== Contract the cluster

.About this task
The desired high-availability (HA) pair of nodes in the cluster are selected to prepare for cluster contraction during the procedure.

.Steps
. Sign in to the Deploy utility web user interface using the administrator account.

. Select the *Cluster* tab at the top of the page and select the desired cluster from the list.

. On the cluster details page, select the gear icon at the right of the page, then select *Contract Cluster*.

. Select the HA Pair configuration details for any HA Pair you want to remove and provide the ONTAP credentials, then select *Contract Cluster*.
+
It can take up to 30 minutes for the cluster to be contracted.

. Monitor the multi-step cluster contraction process to confirm that the cluster contracted successfully.

. Refer to the events tab for periodic updates on the operation's progress. The page is automatically refreshed at regular intervals.

// 2023 May 06, ONTAPDOC-1797, -1802