---
sidebar: sidebar
permalink: task_cli_deploy_image_add.html
keywords: administer, administering, cli, deploy, ontap select image, add
summary: You can add an ONTAP Select image to your instance of the Deploy administration utility. After the image has been installed, you can use it when deploying an ONTAP Select cluster.
---

= Add an ONTAP Select image to Deploy
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can add an ONTAP Select image to your instance of the Deploy administration utility. After the image has been installed, you can use it when deploying an ONTAP Select cluster.

== Before you begin

At a high level, the process used to add an ONTAP Select image to an instance of Deploy consists of four steps:

. Downloading the install image
. Uploading the install image to the Deploy virtual machine
. Adding the install image
. Displaying the available install images

Before adding any new ONTAP Select images to Deploy, you should first remove any unneeded images.

[NOTE]
You should only add an ONTAP Select image with a version that is earlier than the original version included with your instance of the Deploy utility. Adding later versions of ONTAP Select as they become available from NetApp is not a supported configuration.

== Download the install image

To begin the process of adding an ONTAP Select image to an instance of the Deploy utility, you must download the install image from the NetApp Support Site. The ONTAP Select install image is formatted as a single compressed file.

.Steps

. Access the NetApp Support Site using a web browser and click *Support Quick Links*.

. Click *Download Software* under *Top Tasks* and sign in to the site.

. Click *Find your product*.

. Scroll down and click *ONTAP Select*.

. Under *Other Available Select Software* click *Deploy Upgrade, Node Upgrade, Image Install*.

. Select the desired release of the upgrade package.

. Review the End User License Agreement (EULA) and click *Accept & Continue*.

. Select and download the appropriate package, responding to all prompts as needed for your environment.

== Upload the install image to Deploy

After acquiring the ONTAP Select install image, you must upload the file to the Deploy virtual machine.

.Before you begin

You must have the install image file available on your local workstation. You must also have the password for the Deploy administrator user account.

.About this task
This task describes one method for uploading the file to the Deploy virtual machine. There may be other options more suitable for your environment.

.Step

. In a command shell on your local workstation, upload the image file to the Deploy virtual machine.
+
Example
+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
Example
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....

.Result

The node install file is stored in the home directory of the admin user.

== Add the install image

You can add the ONTAP Select installation image to the Deploy images directory so it is available when deploying a new cluster.

.Before you begin

You must know which directory the install image file has been placed in at the Deploy utility virtual machine. It is assumed the file is in the administrator's home directory.

.Steps

. Sign in to the Deploy utility CLI using SSH with the administrator (admin) account.

. Start the Bash shell:
+
`shell bash`

. Place the install image file into the images directory.
+
Example
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`

== Display the available install images

You can display the ONTAP Select images that are available when deploying a new cluster.

.Steps

. Access the online documentation web page at the Deploy utility virtual machine and sign in using the administrator (admin) account:
+
`\http://<FQDN|IP_ADDRESS>/api/ui`
+
Use the domain name or IP address of the Deploy virtual machine.

. Navigate to the bottom of the page and click *Deploy* and then click *GET /images*.

. Click *Try it out!* to display the available ONTAP Select images.

. Confirm that the desired image is available.
