---
sidebar: sidebar
permalink: ti_adm_deploy_image_remove.html
keywords: ontap select
summary: xxx
---

= Removing ONTAP Select images from the Deploy utility
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can remove ONTAP Select images from your instance of the Deploy administration utility whenthey are no longer needed.

.About this task

You can remove older ONTAP Select images that are not currently in use by a cluster or planned for use with a future cluster deployment.

IMPORTANT: You should not remove any ONTAP Select images that are in use by a cluster.

.Steps

. Sign in to the Deploy utility CLI using SSH with the administrator (admin) account.

. Display the clusters managed by Deploy and record the ONTAP images in use:
+
`cluster show`
+
Note the version number and hypervisor platform in each case.

. Start the Bash shell:
+
`shell bash`

. Display all of the available ONTAP Select images:
+
`ls -lh /opt/netapp/images`

. Optionally remove an ESXi image.

Example
+
`rm -r /opt/netapp/images/DataONTAPv-9.3RC1-vidconsole-esx.ova`

. Optionally remove a KVM image.
+
Example
+
`rm -r /opt/netapp/images/DataONTAPv-9.3RC1-serialconsole-kvm.raw.tar`
