---
sidebar: sidebar
permalink: ti_cli_deploy_cluster.html
keywords: overview, concepts, features, use cases
summary: ONTAP Select allows you xxx
---

= Deploying an ONTAP Select cluster using the CLI
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the command line interface provided with the ONTAP Select Deploy administration utility to create a single-node or multi-node ONTAP Select cluster.

== Before you begin

xxx

==== Decisions
>> Decisions (single node or multiple nodes, production or evaluation)

==== Workflow summary

You must perform several tasks to deploy an ONTAP Select cluster in a production environment. At a high level, these steps include:

. Upload and register the license files
. Add the hypervisor hosts
. ETC

==== Additional considerations

Before creating an ONTAP Select cluster on the ESXi hypervisor, you should note the following:

Preparing to attach storage to the ONTAP Select node::
If you use a local hardware RAID controller, you must create at least one storage pool at each node for the system data as well as the root and data aggregates. You must attach the storage pool as part of configuring the ONTAP Select node.

If you use software RAID, you must create a storage pool for the system data and make sure the SSD drives are available for the root and data aggregates. You must attach the storage pool and disks as part of configuring the ONTAP Select node.

Available ONTAP Select versions::
The Deploy administration utility contains a single version of ONTAP Select. If you want to deploy clusters using an earlier version of ONTAP Select, you must first add the ONTAP Select image to your Deploy instance. See _Adding an ONTAP Select image to the Deploy utility_ for more information.

Licensing ONTAP Select for a production deployment::
Before deploying an ONTAP Select cluster in a production environment, you must purchase a storage capacity license and download the associated license file. You can license the storage at each node using the _capacity tiers_ model or license a shared pool using the _capacity pools_ model.

== Uploading and registering a license

After acquiring a license file with storage capacity, you must upload the file containing the license to the Deploy virtual machine and register it.

.Before you begin

You must have uploaded the license file to the Deploy virtual machine. Also, you must have the password for the admin user account.

.Steps

. In a command shell on your local workstation, use the sftp utility to upload the license file to the Deploy virtual machine.
+
`sftp admin@10.234.81.101 (provide password when prompted)`
`put NLF-320000nnn.txt`
`exit`

. Sign in to the Deploy utility CLI using SSH with the administrator account.

. Register the license:
+
`license add -file-name FILENAME`
+
Provide the administrator account password when prompted.

. Display the licenses in the system to confirm the license was added properly:
+
`license show`

== Adding the ESXi hypervisor hosts

You must register each hypervisor host where an ONTAP Select node will run. As part of this, the Deploy administration utility authenticates either to the vCenter server managing the host or directly to the ESXi standalone host.

.About this task

Before you register a host that is managed by vCenter, you must add an account credential for the vCenter server. If the host is not managed by vCenter, you can provide the host credential as part of registering the host. You should use this procedure to add each host.

.Steps

. Sign in to the Deploy utility CLI using SSH with the administrator account.

. If the host is managed by a vCenter server, add the vCenter account credential:
+
`credential add -hostname <FQDN|IP> -type vcenter -username VCENTER_USERNAME`
+
Example:
+
`credential add -hostname vc.select.company-demo.com -type vcenter -username administrator@vsphere.local`

. Register the host:

* Register a standalone host not managed by vCenter:
`host register -name <FQDN|IP> -hypervisor-type ESX -username ESX_USERNAME`

* Register a host managed by vCenter:
`host register -name <FQDN|IP> -hypervisor-type ESX -mgmt-server <FQDN| IP>`
