---
sidebar: sidebar
permalink: ti_cli_upgrade_deploy.html
keywords: ontap select
summary: xxx
---

= Upgrading a Deploy instance
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can upgrade an existing Deploy utility virtual machine in-place using the command line interface.

[cols="1"]
|===
|*Draft comment:*
ONTAP Select 9.7 RC1 - Clear browser cache after applying the upgrade package.
{set:cellbgcolor:yellow}
|===

== Before you begin

It is recommended that you back up the configuration of the Deploy virtual machine before beginning the upgrade. Make sure that Deploy is not used to perform any other tasks during the upgrade.

You should see the current release notes for information and restrictions about upgrading the Deploy utility.

== Downloading the upgrade package

To begin the upgrade process, you must download the appropriate Deploy virtual machine upgrade file from the NetApp Support Site. The upgrade package is formatted as a single compressed file.

.Steps

. Access the NetApp Support Site using a web browser and click *Support Quick Links*.

. Click *Download Software* under *Top Tasks* and sign in.

. Click *Find your product*.

. Scroll down and click *ONTAP Select Deploy Upgrade*.

. Select the desired release of the upgrade package.

. Review the End User License Agreement (EULA) and click *Accept & Continue*.

. Select and download the appropriate package, responding to all prompts as needed for your environment.

.Related information
link:https://mysupport.netapp.com[NetApp Support^]

== Uploading the package to the Deploy virtual machine

After acquiring the upgrade package, you must upload the file to the Deploy virtual machine.

.Before you begin

You must have the upgrade file available on your local workstation. You must also have the password for the administrator user account.

.About this Tasks

This task describes one method for uploading the file to the Deploy virtual machine. There may be other options more suitable for your environment.

.Steps

. In a command shell on your local workstation, use the sftp utility to upload the image file to the Deploy virtual machine.
+
Example
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put ONTAPdeploy2.8_upgrade.tar.gz
exit
....

.Result
The upgrade file is stored in the home directory of the admin user.


== Applying the upgrade package

After the upgrade file has been uploaded to the Deploy virtual machine, you can apply the upgrade.

.Before you begin
You must known which directory the upgrade file has been placed in at the Deploy utility virtual machine. Also, assure that Deploy is not used to perform any other tasks while the upgrade is performed.

.Steps

. Sign in to the Deploy utility CLI using SSH with the administrator account.
. Perform the upgrade using the appropriate directory path and file name:
+
`deploy upgrade -package-path FILEPATH`
+
Example
+
....
deploy upgrade -package-path /home/admin/
ONTAPdeploy2.10_upgrade.tar.gz
....

.After you finish

It is recommended that you back up the configuration of the Deploy virtual machine after the upgrade procedure is completed. You should clear the browser cache to be able to view the newly created Deploy pages.
