---
sidebar: sidebar
permalink: ti_install_deploy.html
keywords: ontap select
summary: You need to install the ONTAP Select Deploy administration utility and use the utility to create an ONTAP Select cluster.
---

= Installing ONTAP Select Deploy
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You need to install the ONTAP Select Deploy administration utility and use the utility to create an ONTAP Select cluster.

== Downloading the virtual machine image

You can download the ONTAP Select package from the NetApp support site.

.About this task
The ONTAP Select Deploy administration utility is packaged as a virtual machine based on the Open Virtualization Format (OVF) standard. The single compressed file has the suffix `ova`.

.Steps
. Access the NetApp support site using a web browser and click *Support Quick Links*.

. Click *Download Software* under *Top Tasks* and sign in.

. Click *Find your product*.

. Scroll down and click *ONTAP Select*.

. Select the desired release of the package.

. Review the End User License Agreement (EULA) and click *Accept & Continue*.

. Select and download the appropriate package, responding to all prompts as needed.

== Deploying the virtual machine

You must install and start the ONTAP Select Deploy virtual machine using the OVF virtual machine image. As part of the installation process, you must configure the network interface to use DHCP or a static IP configuration.

.Before you begin
You must prepare to deploy the ONTAP Select Deploy virtual machinea;

* Enable the OVF functionality in your browser by installing the VMware Client Integration Plugin or performing similar configuration as needed
* Enabled DHCP in the VMware environment if you will dynamically assign an IP address to the Deploy virtual machine

You must have the configuration information to be used when creating the virtual machine, including the name of the virtual machine, external network, and host name. When defining a static network configuration, you need the following additional information:

* IP address of the Deploy virtual machine
* Netmask
* IP address of the gateway (router)
* IP address of the primary DNS server
* IP address of the second DNS server
* DNS search domains

.About this task
If you use vSphere, the Deploy OVF template wizard includes a form to provide all of the Deploy configuration information, including the network configuration. However, if you choose not to use this form, you can use the console of the Deploy virtual machine to configure the network instead.

.Steps

. Access the vSphere client and sign in.

. Navigate to the appropriate location in the hierarchy and select *Deploy OVF Template*.

. Select the OVA file and complete the Deploy OVF Template wizard, selecting the options as appropriate for your environment.
+
You must define the password for the administrator account. You need to provide this password when signing in to the Deploy utility.

. After the virtual machine is deployed, select the new virtual machine and power it on if it is not already powered on based on your input to the deployment wizard.

. If needed, you can configure the Deploy network using the virtual machine console:
.. Click the *Console* tab to access the ESXi host setup shell and monitor the power on process.
.. Wait for the following prompt:
+
Host name :
.. Type the host name and press *Enter*.
.. Wait for the following prompt:
+
Use DHCP to set networking information? [n]:
.. Type *n* to define a static IP configuration or y to use DHCP, and press *Enter*.
.. If you choose a static configuration, provide all network configuration information as required.

== Signing in to the Deploy web interface

You should sign in to the web user interface to confirm the Deploy utility is available and perform initial configuration.

.Steps
. Point your browser to the Deploy utility using the IP address or domain name:
+
`https://<ip_address>/`

. Provide the account information and sign in.

. If the *Welcome to ONTAP Select* popup window is displayed, review the prerequisites and click *OK* to continue.

. If this is the first time signing in and you did not install Deploy using the wizard available with vCenter, provide the following configuration information when prompted:
+
* New password for the administrator account (required)
* AutoSupport (optional)
* vCenter server with account credentials (optional)

.Related information

link:ti_cli_signing_in.html[Signing in to Deploy using SSH]
