---
sidebar: sidebar
permalink: ti_vpi_upgrade.html
keywords: ontap select
summary: xxx
---

= Upgrading, removing, and verifying the Deploy vCenter plug-in
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the ONTAP Select Deploy web user interface to upgrade or remove the Deploy plug-in from the vCenter server. You can also verify that the plug-in is still installed.

[cols="1"]
|===
|*Draft comment:*
ONTAP Select 9.7 RC1 - MUST REVIEW AND UPDATE
{set:cellbgcolor:yellow}
|===

.Before you begin

* Review link:ci_vpi_manage_before.html[Before you begin].
* The VMware vCenter plug-in should be installed and registered.
* The vCenter administrator account must have the following vCenter privileges:
** Extension
*** Update extension
*** Unregister extension

.Steps

. Sign in to the Deploy utility using the administrator account.

. Click the *Administration* tab at the top of the page and then click *Plugins* in the pane on the left.

.After you finish

If you remove the plug-in, you must perform one of the following tasks to complete its removal from the vCenter server:

* Reboot the vCenter server
* Manually remove the plug-in from the vCenter server
