---
sidebar: sidebar
permalink: ti_vpi_upgrade.html
keywords: ontap select
summary: xxx
---

= xxx
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
xxx

Upgrading, removing, and verifying the Deploy vCenter plug-in
You can use the ONTAP Select Deploy web user interface to upgrade or remove the Deploy
plug-in from the vCenter server. You can also verify that the plug-in is still installed.
Before you begin
• Review Planning to manage the vCenter plug-in.
• The VMware vCenter plug-in should be installed and registered.
• The vCenter administrator account must have the following vCenter privileges:
Extension
Update extension
Unregister extension
Steps
1. Sign in to the Deploy utility using the administrator account.
2. Click the Administration tab at the top of the page and then click Plugins in the pane
on the left.
3. Select the plug-in on the Registered Plugins page and click the appropriate icon to
perform the desired action.
+
[cols="15,85"*,options="header"]
|===

|Click this icon ...
|To do the following ...

|Trash can
|Remove the Deploy plug-in from the Deploy utility and the vCenter server.

|Up arrow
|Upgrade the Deploy plug-in in vCenter. Enter the requested information in the wizard and click *Upgrade*.

|Check mark
|Verify the Deploy plug-in. A green check mark indicates that the plug-in is still installed in vCenter and is still operational.

.After you finish

If you remove the plug-in, you must perform one of the following tasks to complete its removal from the vCenter server:

* Reboot the vCenter server
* Manually remove the plug-in from the vCenter server
